// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 yuubinnkyoku
// Host-only byte-level generation helper for private Nicopedia checkpoints.
// Loads an NPRTCKPTV1 checkpoint and runs greedy or deterministic top-K
// sampling on the CPU reference path.  Outputs generated bytes (hex) plus
// aggregate counts/metrics only; the private checkpoint itself never enters
// the repository.
#include "nicopedia_generation.h"
#include "tiny_language_model_cpu.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
constexpr std::uint64_t kFnvOffset = 1469598103934665603ull;
constexpr std::uint64_t kFnvPrime = 1099511628211ull;

std::uint64_t fnvBytes(const void* data, std::size_t bytes,
                       std::uint64_t hash = kFnvOffset) {
  const auto* input = static_cast<const std::uint8_t*>(data);
  for (std::size_t i = 0; i < bytes; ++i) {
    hash ^= input[i];
    hash *= kFnvPrime;
  }
  return hash;
}

std::uint32_t readU32(std::istream& input) {
  std::array<std::uint8_t, 4> bytes{};
  input.read(reinterpret_cast<char*>(bytes.data()),
             static_cast<std::streamsize>(bytes.size()));
  if (!input) throw std::runtime_error("TRUNCATED_U32");
  return (std::uint32_t(bytes[0]) << 24) | (std::uint32_t(bytes[1]) << 16) |
         (std::uint32_t(bytes[2]) << 8) | std::uint32_t(bytes[3]);
}

std::uint64_t readU64(std::istream& input) {
  std::array<std::uint8_t, 8> bytes{};
  input.read(reinterpret_cast<char*>(bytes.data()),
             static_cast<std::streamsize>(bytes.size()));
  if (!input) throw std::runtime_error("TRUNCATED_U64");
  std::uint64_t value = 0;
  for (std::uint8_t byte : bytes) value = (value << 8) | byte;
  return value;
}

struct Checkpoint {
  phonelm::tiny_lm::Config config;
  std::uint32_t seed = 0;
  std::uint32_t step = 0;
  phonelm::qnn::TinyTransformerParameters parameters;
};

Checkpoint loadCheckpoint(const std::string& path) {
  std::ifstream input(path, std::ios::binary);
  if (!input) throw std::runtime_error("CHECKPOINT_OPEN_FAILED");
  std::string magic(11, '\0');
  input.read(magic.data(), static_cast<std::streamsize>(magic.size()));
  if (magic != "NPRTCKPTV1\n") throw std::runtime_error("CHECKPOINT_MAGIC");
  Checkpoint checkpoint;
  checkpoint.config.vocabularySize = readU32(input);
  checkpoint.config.tokens = readU32(input);
  checkpoint.config.dimension = readU32(input);
  checkpoint.config.feedForwardDimension = readU32(input);
  checkpoint.config.numLayers = readU32(input);
  checkpoint.config.numHeads = readU32(input);
  checkpoint.seed = readU32(input);
  checkpoint.step = readU32(input);
  checkpoint.parameters =
      phonelm::tiny_lm::initialParameters(checkpoint.config, checkpoint.seed);
  auto registry = phonelm::tiny_lm::parameterRegistry(checkpoint.parameters);
  const std::uint32_t count = readU32(input);
  if (count != registry.size())
    throw std::runtime_error("CHECKPOINT_REGISTRY_COUNT");
  for (std::uint32_t group = 0; group < count; ++group) {
    const std::uint32_t nameLength = readU32(input);
    if (nameLength > 256) throw std::runtime_error("CHECKPOINT_NAME_LENGTH");
    std::string name(nameLength, '\0');
    input.read(name.data(), static_cast<std::streamsize>(name.size()));
    const std::uint64_t values = readU64(input);
    if (!input || name != registry[group].name ||
        values != registry[group].values->size())
      throw std::runtime_error("CHECKPOINT_REGISTRY_IDENTITY");
    auto& destination = *const_cast<std::vector<float>*>(registry[group].values);
    input.read(
        reinterpret_cast<char*>(destination.data()),
        static_cast<std::streamsize>(destination.size() * sizeof(float)));
    if (!input) throw std::runtime_error("CHECKPOINT_VALUES_TRUNCATED");
  }
  if (input.get() != std::char_traits<char>::eof())
    throw std::runtime_error("CHECKPOINT_TRAILING_BYTES");
  return checkpoint;
}

bool allFinite(const std::vector<float>& values) {
  return std::all_of(values.begin(), values.end(),
                     [](float value) { return std::isfinite(value); });
}

bool parametersFinite(const phonelm::qnn::TinyTransformerParameters& parameters) {
  for (const auto& info : phonelm::tiny_lm::parameterRegistry(parameters)) {
    if (!allFinite(*info.values)) return false;
  }
  return true;
}

std::uint64_t parameterHash(const phonelm::qnn::TinyTransformerParameters& parameters) {
  std::uint64_t hash = kFnvOffset;
  for (const auto& info : phonelm::tiny_lm::parameterRegistry(parameters)) {
    hash = fnvBytes(info.name.data(), info.name.size(), hash);
    const std::uint64_t count = info.values->size();
    hash = fnvBytes(&count, sizeof(count), hash);
    hash = fnvBytes(info.values->data(), info.values->size() * sizeof(float), hash);
  }
  return hash;
}

std::vector<float> multiply(const std::vector<float>& a, const std::vector<float>& b,
                            std::uint32_t rows, std::uint32_t inner,
                            std::uint32_t columns) {
  std::vector<float> result(std::size_t(rows) * columns);
  for (std::uint32_t row = 0; row < rows; ++row) {
    for (std::uint32_t column = 0; column < columns; ++column) {
      double sum = 0;
      for (std::uint32_t index = 0; index < inner; ++index)
        sum += double(a[std::size_t(row) * inner + index]) *
               b[std::size_t(index) * columns + column];
      result[std::size_t(row) * columns + column] = float(sum);
    }
  }
  return result;
}

std::vector<float> normalize(const phonelm::tiny_lm::Config& config,
                             const std::vector<float>& input,
                             const std::vector<float>& gamma,
                             const std::vector<float>& beta) {
  std::vector<float> result(input.size());
  for (std::uint32_t row = 0; row < config.tokens; ++row) {
    double mean = 0;
    for (std::uint32_t d = 0; d < config.dimension; ++d)
      mean += input[std::size_t(row) * config.dimension + d];
    mean /= config.dimension;
    double variance = 0;
    for (std::uint32_t d = 0; d < config.dimension; ++d) {
      const double centered = input[std::size_t(row) * config.dimension + d] - mean;
      variance += centered * centered;
    }
    variance /= config.dimension;
    const double inverse = 1.0 / std::sqrt(variance + config.epsilon);
    for (std::uint32_t d = 0; d < config.dimension; ++d) {
      const std::size_t index = std::size_t(row) * config.dimension + d;
      result[index] = float((input[index] - mean) * inverse) * gamma[d] + beta[d];
    }
  }
  return result;
}

void addInPlace(std::vector<float>& target, const std::vector<float>& addition) {
  if (target.size() != addition.size())
    throw std::runtime_error("INFERENCE_SHAPE_MISMATCH");
  for (std::size_t i = 0; i < target.size(); ++i) target[i] += addition[i];
}

const phonelm::qnn::TinyTransformerLayerParameters& layer(
    const phonelm::qnn::TinyTransformerParameters& parameters,
    std::uint32_t index) {
  if (index == 0)
    return static_cast<const phonelm::qnn::TinyTransformerLayerParameters&>(parameters);
  return parameters.layers.at(index - 1);
}

struct Inference {
  std::vector<float> logits;
  std::vector<float> probabilities;
};

Inference infer(const phonelm::tiny_lm::Config& config,
                const std::vector<std::uint32_t>& tokens,
                const phonelm::qnn::TinyTransformerParameters& parameters) {
  if (tokens.size() != config.tokens)
    throw std::runtime_error("INFERENCE_TOKEN_COUNT");
  std::vector<float> input(std::size_t(config.tokens) * config.dimension);
  for (std::uint32_t row = 0; row < config.tokens; ++row) {
    if (tokens[row] >= config.vocabularySize)
      throw std::runtime_error("INFERENCE_TOKEN_RANGE");
    const std::size_t source = std::size_t(tokens[row]) * config.dimension;
    const std::size_t destination = std::size_t(row) * config.dimension;
    std::copy_n(parameters.tokenEmbedding.begin() +
                    static_cast<std::ptrdiff_t>(source),
                config.dimension,
                input.begin() + static_cast<std::ptrdiff_t>(destination));
  }
  addInPlace(input, phonelm::tiny_lm::fixedPosition(config));
  const std::uint32_t headDimension = config.dimension / config.numHeads;
  const float scale = 1.0f / std::sqrt(float(headDimension));
  for (std::uint32_t layerIndex = 0; layerIndex < config.numLayers; ++layerIndex) {
    const auto& weights = layer(parameters, layerIndex);
    const auto norm1 = normalize(config, input, weights.gamma1, weights.beta1);
    const auto q = multiply(norm1, weights.wq, config.tokens, config.dimension,
                            config.dimension);
    const auto k = multiply(norm1, weights.wk, config.tokens, config.dimension,
                            config.dimension);
    const auto v = multiply(norm1, weights.wv, config.tokens, config.dimension,
                            config.dimension);
    std::vector<float> context(std::size_t(config.tokens) * config.dimension);
    for (std::uint32_t head = 0; head < config.numHeads; ++head) {
      for (std::uint32_t row = 0; row < config.tokens; ++row) {
        float maximum = -std::numeric_limits<float>::infinity();
        std::vector<float> scores(config.tokens,
                                  -std::numeric_limits<float>::infinity());
        for (std::uint32_t column = 0; column <= row; ++column) {
          double score = 0;
          for (std::uint32_t d = 0; d < headDimension; ++d)
            score += double(q[std::size_t(row) * config.dimension +
                              head * headDimension + d]) *
                     k[std::size_t(column) * config.dimension +
                       head * headDimension + d];
          scores[column] = float(score) * scale;
          maximum = std::max(maximum, scores[column]);
        }
        double sum = 0;
        for (std::uint32_t column = 0; column <= row; ++column) {
          scores[column] = std::exp(scores[column] - maximum);
          sum += scores[column];
        }
        for (std::uint32_t column = 0; column <= row; ++column) {
          const float probability = scores[column] / float(sum);
          for (std::uint32_t d = 0; d < headDimension; ++d)
            context[std::size_t(row) * config.dimension +
                    head * headDimension + d] +=
                probability *
                v[std::size_t(column) * config.dimension +
                  head * headDimension + d];
        }
      }
    }
    auto residual = input;
    addInPlace(residual,
               multiply(context, weights.wo, config.tokens, config.dimension,
                        config.dimension));
    const auto norm2 = normalize(config, residual, weights.gamma2, weights.beta2);
    auto hidden = multiply(norm2, weights.w1, config.tokens, config.dimension,
                           config.feedForwardDimension);
    for (float& value : hidden) value = std::max(0.0f, value);
    input = residual;
    addInPlace(input,
               multiply(hidden, weights.w2, config.tokens,
                        config.feedForwardDimension, config.dimension));
  }
  Inference result;
  result.logits = multiply(input, parameters.outputProjection, config.tokens,
                           config.dimension, config.vocabularySize);
  result.probabilities.resize(result.logits.size());
  for (std::uint32_t row = 0; row < config.tokens; ++row) {
    const std::size_t base = std::size_t(row) * config.vocabularySize;
    const float maximum =
        *std::max_element(result.logits.begin() + static_cast<std::ptrdiff_t>(base),
                          result.logits.begin() +
                              static_cast<std::ptrdiff_t>(base + config.vocabularySize));
    double sum = 0;
    for (std::uint32_t token = 0; token < config.vocabularySize; ++token) {
      result.probabilities[base + token] =
          std::exp(result.logits[base + token] - maximum);
      sum += result.probabilities[base + token];
    }
    for (std::uint32_t token = 0; token < config.vocabularySize; ++token)
      result.probabilities[base + token] /= float(sum);
  }
  return result;
}

std::string lower(std::string value) {
  std::transform(value.begin(), value.end(), value.begin(),
                 [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
  return value;
}
}  // namespace

int main(int argc, char** argv) {
  try {
    if (argc < 5 || argc > 8) {
      std::cerr << "usage: nicopedia_cpu_generate CHECKPOINT PROMPT_HEX MODE "
                   "MAX_NEW_BYTES [TEMPERATURE] [TOP_K] [SAMPLING_SEED]\n";
      return 2;
    }
    const Checkpoint checkpoint = loadCheckpoint(argv[1]);
    const std::vector<std::uint8_t> promptBytes =
        phonelm::nicopedia_gen::hexToBytes(argv[2]);
    const std::string mode = lower(argv[3]);
    const std::uint32_t maxNewBytes =
        static_cast<std::uint32_t>(std::stoul(argv[4]));
    const float temperature = argc > 5 ? std::stof(argv[5]) : 1.0f;
    const std::uint32_t topK = argc > 6 ? static_cast<std::uint32_t>(std::stoul(argv[6])) : 256;
    const std::uint64_t samplingSeed = argc > 7 ? std::stoull(argv[7]) : 0ull;
    if (maxNewBytes == 0 || maxNewBytes > 1024)
      throw std::runtime_error("MAX_NEW_BYTES_RANGE");
    if (!parametersFinite(checkpoint.parameters))
      throw std::runtime_error("CHECKPOINT_PARAMETERS_NONFINITE");

    const bool greedy = mode == "greedy";
    if (!greedy && mode != "sample")
      throw std::runtime_error("MODE_MUST_BE_GREEDY_OR_SAMPLE");

    std::uint32_t padBytes = 0;
    std::vector<std::uint8_t> context =
        phonelm::nicopedia_gen::buildGenerationContext(
            promptBytes, checkpoint.config.tokens, &padBytes);
    if (context.size() != checkpoint.config.tokens)
      throw std::runtime_error("CONTEXT_SIZE_MISMATCH");

    std::vector<std::uint8_t> generated;
    generated.reserve(maxNewBytes);
    bool finite = true;
    for (std::uint32_t step = 0; step < maxNewBytes; ++step) {
      std::vector<std::uint32_t> tokens(context.size());
      for (std::size_t i = 0; i < context.size(); ++i) tokens[i] = context[i];
      const Inference output = infer(checkpoint.config, tokens, checkpoint.parameters);
      finite = finite && allFinite(output.logits) && allFinite(output.probabilities);
      const std::size_t base =
          std::size_t(checkpoint.config.tokens - 1) * checkpoint.config.vocabularySize;
      const uint8_t byte =
          greedy ? phonelm::nicopedia_gen::greedyArgmax(output.logits.data() + base,
                                                       checkpoint.config.vocabularySize)
                 : phonelm::nicopedia_gen::sampleTopK(
                       output.logits.data() + base, checkpoint.config.vocabularySize,
                       temperature, topK, samplingSeed, static_cast<std::uint64_t>(step));
      generated.push_back(byte);
      phonelm::nicopedia_gen::appendByteWindow(context, byte);
    }

    const auto stats = phonelm::nicopedia_gen::utf8StatsOf(generated);
    const auto ag = phonelm::nicopedia_gen::generationAggregates(generated);

    std::cout << "NICOPEDIA_CPU_GENERATION\n"
              << "test=nicopedia_cpu_generation\n"
              << "status=SUCCESS\n"
              << "model=L" << checkpoint.config.numLayers << "\n"
              << "layers=" << checkpoint.config.numLayers << "\n"
              << "seed=" << checkpoint.seed << "\n"
              << "checkpoint_step=" << checkpoint.step << "\n"
              << "parameter_hash=fnv1a64:" << std::hex << std::setw(16)
              << std::setfill('0') << parameterHash(checkpoint.parameters) << std::dec
              << "\ngenerate_mode=" << (greedy ? "greedy" : "sample") << "\n"
              << "temperature=" << std::setprecision(10) << temperature << "\n"
              << "top_k=" << topK << "\n"
              << "sampling_seed=" << samplingSeed << "\n"
              << "max_new_bytes=" << maxNewBytes << "\n"
              << "prompt_byte_count=" << promptBytes.size() << "\n"
              << "context_used_bytes=" << checkpoint.config.tokens << "\n"
              << "context_padding_bytes=" << padBytes << "\n"
              << "generated_byte_count=" << generated.size() << "\n"
              << "generated_valid_utf8_bytes=" << stats.validBytes << "\n"
              << "generated_invalid_utf8_bytes=" << stats.invalidBytes << "\n"
              << "generated_hex=" << phonelm::nicopedia_gen::bytesToHex(generated) << "\n"
              << "unique_byte_values=" << ag.uniqueByteValues << "\n"
              << "ascii_bytes=" << ag.asciiBytes << "\n"
              << "max_same_byte_run=" << ag.maxSameByteRun << "\n"
              << "max_scalar_repeat_run=" << ag.maxScalarRepeatRun << "\n"
              << "short_period_loop_fraction=" << std::setprecision(17)
              << ag.shortPeriodLoopFraction << "\n"
              << "finite=" << (finite ? "true" : "false") << "\n";
    return 0;
  } catch (const std::exception& error) {
    std::cerr << "nicopedia_cpu_generate_error=" << error.what() << '\n';
    return 1;
  }
}
