// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 yuubinnkyoku

#pragma once
#include "../nicopedia_generation.h"
#include "../tiny_language_model_cpu.h"
#include "../training_engine.h"
#include "qnn_runtime.h"
#include <atomic>
#include <cstdint>
#include <string>
#include <vector>
namespace phonelm::qnn {
std::string runTransformerExperiment(ExecutionMode mode);
std::string runTinyTransformerTrainingExperiment(
    ExecutionMode mode, const TrainingConfig& trainingConfig,
    const LogSink& progress, std::atomic_bool* stopRequested = nullptr);
// Nicopedia byte-level generation on the HTP graph (device-side loop).
// `checkpointPath`/`promptPath` are app-private files; the checkpoint is the
// NPRTCKPTV1 private checkpoint written by the HTP training milestone and its
// header/seed/step/registry identity is validated fail-closed on load.  The
// returned report is private (KEY=VALUE): it contains the generated bytes in
// hex and must never enter public artifacts.
std::string runNicopediaHtpGeneration(
    const tiny_lm::Config& config, const std::string& checkpointPath,
    const std::string& promptPath, const TrainingConfig& trainingConfig,
    const nicopedia_gen::GenerateConfig& generateConfig,
    const LogSink& progress);
// Private-device diagnostic entry. The payload is the fail-closed
// phonelm.qnn.first_nonfinite codec, never a public result artifact.
std::string replayFirstNonfiniteCheckpoint(
    const std::vector<std::uint8_t>& payload, std::uint32_t repeatCount = 2,
    TinyTransformerTrainingTapSet tapSet = TinyTransformerTrainingTapSet::NONE);
// Private CPU/HTP divergence localization on the fixed parity prefixes.
// `config` must be the L19/H2 Nicopedia configuration; the HTP graph is
// prepared once per tap scope ("NONE" | "COARSE" | "FINE") and every parity
// prefix is compared at the coarse layer-output boundaries or the single
// selected fine layer.  Returns the private KEY=VALUE diagnostic report.
std::string runNicopediaHtpDivergenceLocalization(
    const tiny_lm::Config& config, const std::string& checkpointPath,
    const nicopedia_gen::GenerateConfig& generateConfig,
    const LogSink& progress);
}
