# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 yuubinnkyoku
# Nicopedia byte-level HTP generation runner.
#
# Stages the HTP-trained private checkpoint (build/reports/nicopedia-htp-training)
# and an arbitrary Japanese prompt (UTF-8 bytes) into the app-private files
# directory, then drives QNN_HTP_TINY_LANGUAGE_MODEL_NICOPEDIA_GENERATE.
# The device runs the full autoregressive loop (fixed-prefix CPU/HTP parity,
# 8-step AR parity, then greedy/sampled generation) on the HTP graph; only
# generated private bytes (hex) plus aggregate metrics return in the report.
#
# The prompt text and the generated bytes NEVER enter public artifacts or the
# private state dir (only counts and SHA-256 fingerprints do).  Terminal
# output may show the lossless \xNN-escaped display.
param(
    [string]$Model = '',                 # L6 | L19 (required)
    [int]$Seed = 0,                      # L6: 1/2/4, L19: 1
    [string]$Prompt = '',                # arbitrary Japanese text
    [string]$PromptFile = '',            # alternative: raw UTF-8 bytes file
    [int]$MaxNewBytes = 64,              # 1..1024
    [string]$Mode = 'Greedy',            # Greedy | Sample
    [double]$Temperature = 1.0,
    [int]$TopK = 256,
    [uint32]$SamplingSeed = 0,
    [string]$QairtSdkRoot = '',
    [string]$ExpectedBuildId = '',
    [switch]$SkipBuild,
    [switch]$SkipInstall,
    [int]$PollLimit = 600,
    [int]$CheckpointStep = 320,
    [string]$GatePolicy = 'legacy',   # legacy | candidate (protocol F)
    [switch]$CandidatePolicyApproved, # required to run -GatePolicy candidate
    [switch]$AuditOnly,               # accept a FAILED gate report (audit runs)
    [int]$HtpGraphPrecisionMode = 0,  # private diagnostics: 0 unset, 1 fp16, 2 fp32
    [int]$HtpGraphPrecisionCompensation = 0,  # private diagnostics: 0 unset, 1 false, 2 true
    [int]$HtpGraphWeightsPacking = 0,  # private diagnostics: 0 unset, 1 false, 2 true
    [int]$HtpGraphAdvancedActivationFusion = 0,  # private diagnostics: 0 unset, 1 false, 2 true
    [switch]$HtpNativeTensorFp16,  # private diagnostics: declare NATIVE tensors FP16
    [switch]$SelfTest
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'qairt_version.ps1')
. (Join-Path $PSScriptRoot 'nicopedia_generation_aggregates.ps1')
Assert-PhoneLmQairtPinnedArguments -SdkRoot $QairtSdkRoot -ExpectedBuildId $ExpectedBuildId
$root = Split-Path -Parent $PSScriptRoot

$reportRoot = Join-Path $root 'build\reports\nicopedia-htp-generation'
$trainingRoot = Join-Path $root 'build\reports\nicopedia-htp-training'
$stateDir = Join-Path $root 'build\private-diagnostics\nicopedia-htp-generation-goal'
[IO.Directory]::CreateDirectory($reportRoot) | Out-Null
[IO.Directory]::CreateDirectory($stateDir) | Out-Null

function Write-Event([string]$Type, [hashtable]$Fields) {
    $entry = @{ ts = [DateTimeOffset]::UtcNow.ToString('o'); type = $Type } + $Fields
    Add-Content -LiteralPath (Join-Path $stateDir 'events.jsonl') `
        -Value ($entry | ConvertTo-Json -Compress) -Encoding utf8
}

function Get-Sha256Hex([string]$LiteralPath) {
    $hash = Get-FileHash -LiteralPath $LiteralPath -Algorithm SHA256
    return $hash.Hash.ToLowerInvariant()
}

# Lossless UTF-8 display: valid sequences pass through, invalid/truncated
# bytes become \xNN escapes (lowercase).  Mirrors nicopedia_generation.h.
function Get-SafeUtf8Display([byte[]]$Bytes) {
    $out = [System.Text.StringBuilder]::new()
    $pos = 0
    while ($pos -lt $Bytes.Length) {
        $b = $Bytes[$pos]
        $length = 0
        if ($b -lt 0x80) {
            $length = 1
        } elseif ($b -ge 0xC2 -and $b -le 0xDF) {
            $length = 2
        } elseif ($b -ge 0xE0 -and $b -le 0xEF) {
            $length = 3
        } elseif ($b -ge 0xF0 -and $b -le 0xF4) {
            $length = 4
        }
        $valid = $true
        if ($length -gt 0 -and $pos + $length -le $Bytes.Length) {
            for ($i = 1; $i -lt $length; $i++) {
                $c = $Bytes[$pos + $i]
                if ($c -lt 0x80 -or $c -gt 0xBF) { $valid = $false; break }
            }
            if ($length -eq 3 -and $b -eq 0xE0 -and $Bytes[$pos + 1] -lt 0xA0) { $valid = $false }
            if ($length -eq 3 -and $b -eq 0xED -and $Bytes[$pos + 1] -ge 0xA0) { $valid = $false }
            if ($length -eq 4 -and $b -eq 0xF0 -and $Bytes[$pos + 1] -lt 0x90) { $valid = $false }
            if ($length -eq 4 -and $b -eq 0xF4 -and $Bytes[$pos + 1] -ge 0x90) { $valid = $false }
        } else {
            $valid = $false
        }
        if ($valid) {
            [void]$out.Append([System.Text.Encoding]::UTF8.GetString($Bytes, $pos, $length))
            $pos += $length
        } else {
            [void]$out.Append('\x')
            [void]$out.Append($b.ToString('x2'))
            $pos += 1
        }
    }
    return $out.ToString()
}

function Invoke-SelfTest {
    # Safe display mirrors the C++ core (lossless \xNN escapes).
    $cases = @(
        @{ Bytes = [byte[]](0x68, 0x69); Expect = 'hi' },
        @{ Bytes = [byte[]](0xE3, 0x81, 0x93); Expect = [string][char]0x3053 },
        @{ Bytes = [byte[]](0xE3, 0x81); Expect = '\xe3\x81' },
        @{ Bytes = [byte[]](0x61, 0xFF, 0x80, 0x62); Expect = 'a\xff\x80b' },
        @{ Bytes = [byte[]](0xED, 0xA0, 0x80); Expect = '\xed\xa0\x80' }
    )
    foreach ($case in $cases) {
        $actual = Get-SafeUtf8Display -Bytes $case.Bytes
        if ($actual -ne $case.Expect) { throw "SELFTEST_DISPLAY: '$actual' != '$($case.Expect)'" }
    }
    $empty = Get-SafeUtf8Display -Bytes ([byte[]]@())
    if ($empty -ne '') { throw 'SELFTEST_DISPLAY_EMPTY' }

    # CheckpointStep file-name resolution mirrors the device-side
    # nprtParseCheckpointStep contract (htp-seed<S>-l<L>-step<N>.ckpt).
    $ckRoot = Join-Path $env:TEMP ("nicopedia-gen-selftest-" + [guid]::NewGuid().ToString('N'))
    [IO.Directory]::CreateDirectory($ckRoot) | Out-Null
    try {
        $step320Ckpt = Join-Path $ckRoot 'htp-seed1-l19-step320.ckpt'
        $step1000Ckpt = Join-Path $ckRoot 'htp-seed1-l19-step1000.ckpt'
        [IO.File]::WriteAllText($step320Ckpt, 'selftest-320')
        [IO.File]::WriteAllText($step1000Ckpt, 'selftest-1000')
        $anchor320 = Join-Path $ckRoot 'seed1-l19-steps320-result.txt'
        $anchor1000 = Join-Path $ckRoot 'seed1-l19-steps1000-result.txt'
        [IO.File]::WriteAllText($anchor320, "final_parameter_hash=fnv1a64:0123456789abcdef`n")
        [IO.File]::WriteAllText($anchor1000, "final_parameter_hash=fnv1a64:fedcba9876543210`n")
        # Resolve-* helpers must pick the step-driven file names.
        $checkpoint = Join-Path $ckRoot "htp-seed1-l19-step320.ckpt"
        $anchorFile = Join-Path $ckRoot "seed1-l19-steps320-result.txt"
        if (-not (Test-Path -LiteralPath $checkpoint -PathType Leaf) -or
            -not (Test-Path -LiteralPath $anchorFile -PathType Leaf)) {
            throw 'SELFTEST_CHECKPOINT_STEP_320'
        }
        $checkpoint1000 = Join-Path $ckRoot "htp-seed1-l19-step1000.ckpt"
        if (-not (Test-Path -LiteralPath $checkpoint1000 -PathType Leaf) -or
            -not (Test-Path -LiteralPath $anchor1000 -PathType Leaf)) {
            throw 'SELFTEST_CHECKPOINT_STEP_1000'
        }
        # A missing step-N file must fail closed.
        foreach ($missing in @(
                (Join-Path $ckRoot 'htp-seed1-l19-step999999.ckpt'),
                (Join-Path $ckRoot 'htp-seed1-l19-step0.ckpt'))) {
            if (Test-Path -LiteralPath $missing -PathType Leaf) {
                throw 'SELFTEST_CHECKPOINT_STEP_LEAK'
            }
        }
    } finally {
        [IO.Directory]::Delete($ckRoot, $true)
    }

    # Aggregate metrics mirror nicopedia_generation.h GenerationAggregates;
    # the shared helper owns both the implementation and its self-test.
    Test-GenerationAggregateSelfTest

    # SHA-256 fingerprint plumbing.
    $temp = Join-Path $env:TEMP ("nicopedia-gen-selftest-" + [guid]::NewGuid().ToString('N'))
    [IO.Directory]::CreateDirectory($temp) | Out-Null
    try {
        $sample = Join-Path $temp 'prompt.bin'
        [IO.File]::WriteAllBytes($sample, [byte[]](0xE3, 0x81, 0x93))
        $h1 = Get-Sha256Hex $sample
        $h2 = Get-Sha256Hex $sample
        if ($h1 -ne $h2 -or $h1.Length -ne 64) { throw 'SELFTEST_SHA256' }
    } finally {
        [IO.Directory]::Delete($temp, $true)
    }

    # CheckpointStep range gate (mirrors the parameter validation).
    foreach ($bad in @(0, -1, 1000000, 9999999)) {
        if ($bad -ge 1 -and $bad -le 999999) { throw "SELFTEST_CHECKPOINT_STEP_RANGE: $bad" }
    }
    if (-not (320 -ge 1 -and 320 -le 999999)) { throw 'SELFTEST_CHECKPOINT_STEP_320_RANGE' }
    if (-not (1000 -ge 1 -and 1000 -le 999999)) { throw 'SELFTEST_CHECKPOINT_STEP_1000_RANGE' }

    # HTP graph precision diagnostic switch range gate (0=unset, 1=fp16, 2=fp32).
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_GRAPH_PRECISION_RANGE: $bad" }
    }
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_GRAPH_PRECISION_COMPENSATION_RANGE: $bad" }
    }
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_GRAPH_WEIGHTS_PACKING_RANGE: $bad" }
    }
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_GRAPH_ACTIVATION_FUSION_RANGE: $bad" }
    }
    if (-not (0 -ge 0 -and 0 -le 2) -or -not (2 -ge 0 -and 2 -le 2)) {
        throw 'SELFTEST_HTP_GRAPH_PRECISION_VALID_VALUES'
    }
    $fp16Expected = 'false'
    if ($HtpNativeTensorFp16) { $fp16Expected = 'true' }
    if ($fp16Expected -notin @('true', 'false')) {
        throw 'SELFTEST_HTP_NATIVE_TENSOR_FP16_BOOL'
    }
    Write-Host 'run_nicopedia_htp_generate_self_test=PASS'
    exit 0
}

if ($SelfTest) { Invoke-SelfTest }

if ($Model -ne 'L6' -and $Model -ne 'L19') { throw "MODEL_INVALID: Model must be L6 or L19 (got '$Model')" }
$layers = if ($Model -eq 'L19') { 19 } else { 6 }
if ($Seed -lt 1 -or $Seed -gt 99999) { throw 'SEED_INVALID: Seed must be in 1..99999' }
if ($CheckpointStep -lt 1 -or $CheckpointStep -gt 999999) {
    throw 'CHECKPOINT_STEP_INVALID: CheckpointStep must be in 1..999999'
}
if ($MaxNewBytes -lt 1 -or $MaxNewBytes -gt 1024) { throw 'MAX_NEW_BYTES_INVALID: MaxNewBytes must be in 1..1024' }
if ($Mode -ne 'Greedy' -and $Mode -ne 'Sample') { throw 'MODE_INVALID: Mode must be Greedy or Sample' }
if ($GatePolicy -ne 'legacy' -and $GatePolicy -ne 'candidate') { throw 'GATE_POLICY_INVALID: GatePolicy must be legacy or candidate' }
if ($GatePolicy -eq 'candidate' -and -not $CandidatePolicyApproved) {
    throw 'CANDIDATE_POLICY_NOT_APPROVED: -GatePolicy candidate requires -CandidatePolicyApproved (independent Reviewer PASS + explicit instruction)'
}
if ($HtpGraphPrecisionMode -lt 0 -or $HtpGraphPrecisionMode -gt 2) {
    throw 'HTP_GRAPH_PRECISION_MODE_INVALID: must be 0, 1 or 2'
}
if ($HtpGraphPrecisionCompensation -lt 0 -or $HtpGraphPrecisionCompensation -gt 2) {
    throw 'HTP_GRAPH_PRECISION_COMPENSATION_INVALID: must be 0, 1 or 2'
}
if ($HtpGraphWeightsPacking -lt 0 -or $HtpGraphWeightsPacking -gt 2) {
    throw 'HTP_GRAPH_WEIGHTS_PACKING_INVALID: must be 0, 1 or 2'
}
if ($HtpGraphAdvancedActivationFusion -lt 0 -or $HtpGraphAdvancedActivationFusion -gt 2) {
    throw 'HTP_GRAPH_ACTIVATION_FUSION_INVALID: must be 0, 1 or 2'
}
if ($Mode -eq 'Sample') {
    if (-not [double]::IsFinite($Temperature) -or $Temperature -le 0.0) { throw 'TEMPERATURE_INVALID' }
    if ($TopK -lt 1 -or $TopK -gt 256) { throw 'TOPK_INVALID' }
}
if ($Prompt -ne '') {
    $promptBytes = [System.Text.Encoding]::UTF8.GetBytes($Prompt)
} elseif ($PromptFile -ne '') {
    $promptFileFull = [IO.Path]::GetFullPath($PromptFile)
    if (-not (Test-Path -LiteralPath $promptFileFull -PathType Leaf)) { throw "PROMPT_FILE_MISSING: $promptFileFull" }
    $promptBytes = [IO.File]::ReadAllBytes($promptFileFull)
} else {
    throw 'PROMPT_REQUIRED: supply -Prompt or -PromptFile'
}
if ($promptBytes.Length -eq 0) { throw 'PROMPT_EMPTY' }
if ($promptBytes.Length -gt 32) {
    Write-Host "prompt=${Model} seed=$Seed bytes=$($promptBytes.Length) -> device uses last 32 bytes (training window semantics)"
}

# Checkpoint + approved anchor (fail-closed before any device work).
# The checkpoint file name embeds the step (htp-seed<S>-l<L>-step<N>.ckpt);
# the device re-validates the step from the file name and the expected
# checkpoint_step intent, so a stale or mismatched file cannot pass.
$checkpoint = Join-Path $trainingRoot "htp-seed$Seed-l$layers-step$CheckpointStep.ckpt"
$anchorFile = Join-Path $trainingRoot "seed$Seed-l$layers-steps$CheckpointStep-result.txt"
if (-not (Test-Path -LiteralPath $checkpoint -PathType Leaf)) { throw "CHECKPOINT_MISSING: $checkpoint" }
if (-not (Test-Path -LiteralPath $anchorFile -PathType Leaf)) { throw "ANCHOR_MISSING: $anchorFile" }
$anchorText = Get-Content -LiteralPath $anchorFile -Raw
$anchorMatch = [regex]::Match($anchorText, '(?m)^final_parameter_hash=(fnv1a64:[0-9a-f]{16})$')
if (-not $anchorMatch.Success) { throw "ANCHOR_HASH_NOT_FOUND: $anchorFile" }
$anchorHash = $anchorMatch.Groups[1].Value

# Fingerprints computed on the host (never the prompt text itself).
$checkpointSha256 = Get-Sha256Hex $checkpoint
$promptSha256Bytes = [System.Security.Cryptography.SHA256]::Create()
$promptSha256 = [System.BitConverter]::ToString($promptSha256Bytes.ComputeHash($promptBytes)).Replace('-', '').ToLowerInvariant()
Write-Event 'host-staged' @{
    model = $Model; seed = $Seed; checkpoint_step = $CheckpointStep
    prompt_byte_count = $promptBytes.Length
    prompt_truncated = ($promptBytes.Length -gt 32); prompt_sha256 = $promptSha256
    checkpoint_sha256 = $checkpointSha256; anchor_hash = $anchorHash
}

$adb = Join-Path $env:LOCALAPPDATA 'Android\Sdk\platform-tools\adb.exe'
$env:ANDROID_HOME = Join-Path $env:LOCALAPPDATA 'Android\Sdk'
$env:ANDROID_SDK_ROOT = $env:ANDROID_HOME
$package = 'com.yuubinnkyoku.phonelm'
$activity = "$package/.MainActivity"
$apk = Join-Path $root 'app\build\outputs\apk\debug\app-debug.apk'

if (-not $SkipBuild) {
    if (-not (Test-Path -LiteralPath $apk -PathType Leaf)) { throw "APK_MISSING: $apk" }
    Write-Host "apk=$apk"
}

$online = @()
foreach ($line in (& $adb devices)) { if ($line -match '^(\S+)\s+device$') { $online += $Matches[1] } }
if ($online.Count -ne 1) { throw "Expected one online ADB device; found $($online.Count)" }
$device = $online[0]
$serial = ((& $adb -s $device shell getprop ro.serialno) -join '').Trim()
$modelName = ((& $adb -s $device shell getprop ro.product.model) -join '').Trim()
$soc = ((& $adb -s $device shell getprop ro.soc.model) -join '').Trim()
$thermal = ((& $adb -s $device shell dumpsys thermalservice) -join "`n")
$thermalStatus = [regex]::Match($thermal, '(?m)^Thermal Status:\s*(\d+)').Groups[1].Value
$battery = ((& $adb -s $device shell dumpsys battery) -join "`n")
$batteryLevel = [regex]::Match($battery, '(?m)^\s*level:\s*(\d+)').Groups[1].Value
$batteryTemp = [regex]::Match($battery, '(?m)^\s*temperature:\s*(\d+)').Groups[1].Value
if ($thermalStatus -ge 5) { throw "THERMAL_ABORT: android_thermal_status=$thermalStatus" }

function Adb([string[]]$Arguments) {
    $output = & $adb -s $device @Arguments 2>&1
    if ($LASTEXITCODE -ne 0) { throw "ADB command failed (endpoint redacted): $($Arguments -join ' ')`n$output" }
    $output
}

if (-not $SkipInstall) {
    Adb @('install', '-r', $apk) | Out-Null
}

# Stage checkpoint + prompt under the app-private files directory.
$remoteDir = 'files/checkpoints/nicopedia-generation'
Adb @('shell', 'run-as', $package, 'mkdir', '-p', $remoteDir) | Out-Null
$tmpCheckpoint = '/data/local/tmp/nicopedia-gen.ckpt'
$tmpPrompt = '/data/local/tmp/nicopedia-prompt.bin'
$localPrompt = Join-Path $env:TEMP ("nicopedia-prompt-" + [guid]::NewGuid().ToString('N') + '.bin')
try {
    [IO.File]::WriteAllBytes($localPrompt, $promptBytes)
    & $adb -s $device push $checkpoint $tmpCheckpoint | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'CHECKPOINT_PUSH_FAILED' }
    & $adb -s $device push $localPrompt $tmpPrompt | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'PROMPT_PUSH_FAILED' }
} finally {
    Remove-Item -LiteralPath $localPrompt -Force -ErrorAction SilentlyContinue
}
Adb @('shell', 'run-as', $package, 'cp', $tmpCheckpoint, "$remoteDir/htp-seed$Seed-l$layers-step$CheckpointStep.ckpt") | Out-Null
Adb @('shell', 'run-as', $package, 'cp', $tmpPrompt, "$remoteDir/prompt.bin") | Out-Null
Adb @('shell', 'rm', '-f', $tmpCheckpoint, $tmpPrompt) | Out-Null

# Drive the generation mode through the debug intent path.
Adb @('shell', 'am', 'force-stop', $package) | Out-Null
& $adb -s $device shell run-as $package rm -f files/device-test-result.txt 2>$null | Out-Null
$startArgs = @(
    'shell', 'am', 'start', '-W', '-n', $activity,
    '--es', 'phonelm.mode', 'QNN_HTP_TINY_LANGUAGE_MODEL_NICOPEDIA_GENERATE',
    '--es', 'phonelm.checkpoint_dump_dir', 'nicopedia-generation',
    '--es', 'phonelm.seed', [string]$Seed,
    '--ei', 'phonelm.layers', $layers,
    '--ei', 'phonelm.checkpoint_step', $CheckpointStep,
    '--ei', 'phonelm.max_new_bytes', $MaxNewBytes,
    '--es', 'phonelm.generate_mode', $Mode.ToLowerInvariant(),
    '--es', 'phonelm.temperature', $Temperature.ToString([System.Globalization.CultureInfo]::InvariantCulture),
    '--ei', 'phonelm.top_k', $TopK,
    '--es', 'phonelm.sampling_seed', [string]$SamplingSeed,
    '--es', 'phonelm.gate_policy', $GatePolicy,
    '--ei', 'phonelm.htp_graph_precision_mode', $HtpGraphPrecisionMode,
    '--ei', 'phonelm.htp_graph_precision_compensation', $HtpGraphPrecisionCompensation,
    '--ei', 'phonelm.htp_graph_weights_packing', $HtpGraphWeightsPacking,
    '--ei', 'phonelm.htp_graph_activation_fusion', $HtpGraphAdvancedActivationFusion,
    '--ez', 'phonelm.htp_native_tensor_fp16', $HtpNativeTensorFp16
)
$startOutput = & $adb -s $device @startArgs 2>&1
if ($LASTEXITCODE -ne 0) { throw "am start failed (endpoint redacted): $($startArgs -join ' ')`n$startOutput" }

$result = ''
for ($poll = 0; $poll -lt $PollLimit; $poll++) {
    Start-Sleep -Seconds 5
    $line = (& $adb -s $device shell run-as $package cat files/device-test-result.txt 2>$null) -join "`n"
    if ($line -match 'NICOPEDIA_HTP_GENERATION') {
        $result = $line
        break
    }
}
if ($result -eq '') { throw 'DEVICE_RESULT_TIMEOUT' }
if ($result -notmatch '(?m)^status=SUCCESS$') {
    if (-not $AuditOnly) {
        throw "DEVICE_GENERATION_FAILED:`n$result"
    }
    Write-Host 'AUDIT_ONLY: device status != SUCCESS — parity metrics recorded'
}
if ($result -notmatch '(?m)^cpu_fallback=false$') { throw 'DEVICE_CPU_FALLBACK_DETECTED' }
$deviceHashMatch = [regex]::Match($result, '(?m)^checkpoint_parameter_hash=(fnv1a64:[0-9a-f]{16})$')
if (-not $deviceHashMatch.Success) { throw 'DEVICE_PARAMETER_HASH_MISSING' }
if ($deviceHashMatch.Groups[1].Value -ne $anchorHash) {
    throw "CHECKPOINT_IDENTITY_MISMATCH: device=$($deviceHashMatch.Groups[1].Value) anchor=$anchorHash"
}
# The device re-validates the expected step (nprtParseCheckpointStep +
# loaded.step != expectedStep).  Mirror that contract on the host so a
# mismatched checkpoint_step intent cannot slip through a stale report.
$headerStepMatch = [regex]::Match($result, '(?m)^checkpoint_header_step=(\d+)$')
if (-not $headerStepMatch.Success) { throw 'DEVICE_HEADER_STEP_MISSING' }
if ([int]$headerStepMatch.Groups[1].Value -ne $CheckpointStep) {
    throw "CHECKPOINT_STEP_MISMATCH: header=$($headerStepMatch.Groups[1].Value) expected=$CheckpointStep"
}
$parityGate = [regex]::Match($result, '(?m)^parity_gate=(true|false)$').Groups[1].Value
$arGate = [regex]::Match($result, '(?m)^ar_gate=(true|false)$').Groups[1].Value
$generationGate = [regex]::Match($result, '(?m)^generation_gate=(true|false)$').Groups[1].Value
$parityGateCandidate = [regex]::Match($result, '(?m)^parity_gate_candidate=(true|false)$').Groups[1].Value
$arGateCandidate = [regex]::Match($result, '(?m)^ar_gate_candidate=(true|false)$').Groups[1].Value
$gatePolicyReported = [regex]::Match($result, '(?m)^gate_policy=(legacy|candidate)$').Groups[1].Value
if ($gatePolicyReported -ne $GatePolicy) {
    throw "GATE_POLICY_MISMATCH: device=$gatePolicyReported requested=$GatePolicy"
}
$precisionModeReported = [regex]::Match($result, '(?m)^htp_graph_precision_mode=(\d+)$').Groups[1].Value
$precisionCompensationReported = [regex]::Match($result, '(?m)^htp_graph_precision_compensation=(\d+)$').Groups[1].Value
$weightsPackingReported = [regex]::Match($result, '(?m)^htp_graph_weights_packing=(\d+)$').Groups[1].Value
$fusionReported = [regex]::Match($result, '(?m)^htp_graph_activation_fusion=(\d+)$').Groups[1].Value
$nativeFp16Reported = [regex]::Match($result, '(?m)^htp_native_tensor_fp16=(true|false)$').Groups[1].Value
if ($precisionModeReported -eq '' -or $precisionCompensationReported -eq '' -or
    $weightsPackingReported -eq '' -or $fusionReported -eq '' -or $nativeFp16Reported -eq '') {
    throw 'HTP_GRAPH_PRECISION_FIELDS_MISSING: report lacks htp_graph_precision fields'
}
$nativeFp16Expected = 'false'
if ($HtpNativeTensorFp16) { $nativeFp16Expected = 'true' }
if ([int]$precisionModeReported -ne $HtpGraphPrecisionMode -or
    [int]$precisionCompensationReported -ne $HtpGraphPrecisionCompensation -or
    [int]$weightsPackingReported -ne $HtpGraphWeightsPacking -or
    [int]$fusionReported -ne $HtpGraphAdvancedActivationFusion -or
    $nativeFp16Reported -ne $nativeFp16Expected) {
    throw "HTP_GRAPH_PRECISION_MISMATCH: device=($precisionModeReported,$precisionCompensationReported,$weightsPackingReported,$fusionReported,$nativeFp16Reported) requested=($HtpGraphPrecisionMode,$HtpGraphPrecisionCompensation,$HtpGraphWeightsPacking,$HtpGraphAdvancedActivationFusion,$nativeFp16Expected)"
}
if ($parityGateCandidate -eq '' -or $arGateCandidate -eq '') {
    throw 'CANDIDATE_GATE_FIELDS_MISSING: report lacks parity_gate_candidate/ar_gate_candidate'
}
if ($parityGate -ne 'true' -or $arGate -ne 'true' -or $generationGate -ne 'true') {
    if (-not $AuditOnly) {
        throw "GENERATION_GATE_REJECTED parity=$parityGate ar=$arGate generation=$generationGate`n$result"
    }
    Write-Host "AUDIT_ONLY: gate rejected (parity=$parityGate ar=$arGate generation=$generationGate) — parity metrics recorded"
}
$generatedHex = [regex]::Match($result, '(?m)^generated_hex=([0-9a-f]*)$').Groups[1].Value
$generatedBytes = [byte[]]@()
if ($generatedHex.Length -gt 0) {
    $generatedBytes = [byte[]]::new($generatedHex.Length / 2)
    for ($i = 0; $i -lt $generatedHex.Length; $i += 2) {
        $generatedBytes[$i / 2] = [Convert]::ToByte($generatedHex.Substring($i, 2), 16)
    }
}
if (-not $AuditOnly) {
    if ($generatedBytes.Length -ne $MaxNewBytes) {
        throw "GENERATED_BYTE_COUNT_MISMATCH: expected=$MaxNewBytes actual=$($generatedBytes.Length)"
    }
}
$generatedSha256Bytes = [System.Security.Cryptography.SHA256]::Create()
$generatedSha256 = [System.BitConverter]::ToString($generatedSha256Bytes.ComputeHash($generatedBytes)).Replace('-', '').ToLowerInvariant()
$generatedStats = Get-SafeUtf8Display -Bytes $generatedBytes

$thermalAfter = ((& $adb -s $device shell dumpsys thermalservice) -join "`n")
$thermalStatusAfter = [regex]::Match($thermalAfter, '(?m)^Thermal Status:\s*(\d+)').Groups[1].Value
$batteryAfter = ((& $adb -s $device shell dumpsys battery) -join "`n")
$batteryLevelAfter = [regex]::Match($batteryAfter, '(?m)^\s*level:\s*(\d+)').Groups[1].Value
$batteryTempAfter = [regex]::Match($batteryAfter, '(?m)^\s*temperature:\s*(\d+)').Groups[1].Value

$annotated = $result.TrimEnd() + "`n" +
    "host_prompt_sha256=$promptSha256`n" +
    "host_generated_sha256=$generatedSha256`n" +
    "host_checkpoint_sha256=$checkpointSha256`n" +
    "host_anchor_hash=$anchorHash`n" +
    "device_model=$modelName`n" +
    "device_soc=$soc`n" +
    "android_thermal_status_before=$thermalStatus`n" +
    "android_thermal_status_after=$thermalStatusAfter`n" +
    "battery_level_before=$batteryLevel`n" +
    "battery_level_after=$batteryLevelAfter`n" +
    "battery_temperature_c_before=$([int]$batteryTemp / 10.0)`n" +
    "battery_temperature_c_after=$([int]$batteryTempAfter / 10.0)`n" +
    "compile_time_qairt_build_id=$ExpectedBuildId`n" +
    "host_htp_graph_precision_mode=$HtpGraphPrecisionMode`n" +
    "host_htp_graph_precision_compensation=$HtpGraphPrecisionCompensation`n" +
    "host_htp_graph_weights_packing=$HtpGraphWeightsPacking`n" +
    "host_htp_graph_activation_fusion=$HtpGraphAdvancedActivationFusion`n" +
    "host_htp_native_tensor_fp16=$nativeFp16Expected`n" +
    "private_serial_recorded_for_identity_only=true`n"
$reportFile = Join-Path $reportRoot "seed$Seed-l$layers-$($Mode.ToLowerInvariant())-step$CheckpointStep-max$MaxNewBytes-result.txt"
$annotated | Set-Content -LiteralPath $reportFile -Encoding utf8
$annotated | Add-Content -LiteralPath (Join-Path $reportRoot 'device-identity-private.txt') -Encoding utf8

Write-Event 'device-generation-succeeded' @{
    model = $Model; seed = $Seed; mode = $Mode.ToLowerInvariant()
    temperature = $Temperature; top_k = $TopK; sampling_seed = $SamplingSeed
    max_new_bytes = $MaxNewBytes
    generated_byte_count = $generatedBytes.Length
    parity_gate = $parityGate; ar_gate = $arGate; generation_gate = $generationGate
    parity_gate_candidate = $parityGateCandidate; ar_gate_candidate = $arGateCandidate
    gate_policy = $gatePolicyReported
}

# Aggregate-only state (no prompt text, no generated bytes, no serials).
$state = [ordered]@{
    schema = 'nicopedia-htp-generation-goal-v1'
    updated_utc = [DateTimeOffset]::UtcNow.ToString('o')
    last_run = [ordered]@{
        model = $Model; seed = $Seed; layers = $layers
        checkpoint_step = $CheckpointStep
        mode = $Mode.ToLowerInvariant(); temperature = $Temperature
        top_k = $TopK; sampling_seed = $SamplingSeed
        max_new_bytes = $MaxNewBytes
        generated_byte_count = $generatedBytes.Length
        generated_invalid_utf8_bytes = ([regex]::Match($result, '(?m)^generated_invalid_utf8_bytes=(\d+)$').Groups[1].Value -as [int])
        parity_gate = $parityGate; ar_gate = $arGate; generation_gate = $generationGate
        parity_gate_candidate = $parityGateCandidate; ar_gate_candidate = $arGateCandidate
        gate_policy = $gatePolicyReported
    }
    run_count = (Get-Content -LiteralPath (Join-Path $stateDir 'events.jsonl') -ErrorAction SilentlyContinue | Measure-Object).Count
}
[IO.File]::WriteAllText((Join-Path $stateDir 'state.json'),
    ($state | ConvertTo-Json -Depth 6) + "`n", [Text.UTF8Encoding]::new($false))

Write-Host ''
Write-Host "== Nicopedia HTP generation ($Model seed=$Seed) =="
Write-Host "prompt (lossless): $Prompt"
if ($PromptFile -ne '') { Write-Host "prompt file: $PromptFile" }
Write-Host "prompt bytes: $($promptBytes.Length) (context: last 32, device-validated)"
Write-Host "mode=$Mode temp=$Temperature topK=$TopK samplingSeed=$SamplingSeed maxNewBytes=$MaxNewBytes checkpointStep=$CheckpointStep"
Write-Host "parity_gate=$parityGate ar_gate=$arGate generation_gate=$generationGate"
Write-Host "generated bytes: $($generatedBytes.Length)"
Write-Host "generated (lossless display): $generatedStats"
Write-Host "generated_sha256=$generatedSha256"
Write-Host "checkpoint_parameter_hash=$($deviceHashMatch.Groups[1].Value) (anchor match)"
Write-Host "PASS NICOPEDIA_HTP_GENERATION seed=$Seed layers=$layers mode=$($Mode.ToLowerInvariant()) bytes=$($generatedBytes.Length)"
Write-Host "Report: $reportFile"
