# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 yuubinnkyoku
# Nicopedia byte-level HTP generation runner.
#
# Stages the HTP-trained private checkpoint (build/reports/nicopedia-htp-training)
# and an arbitrary Japanese prompt (UTF-8 bytes) into the app-private files
# directory, then drives QNN_HTP_TINY_LANGUAGE_MODEL_NICOPEDIA_GENERATE.
# The device runs the full autoregressive loop (fixed-prefix CPU/HTP parity,
# 8-step AR parity, then greedy/sampled generation) on the HTP graph; only
# generated private bytes (hex) plus aggregate metrics return in the report.
#
# The prompt text and the generated bytes NEVER enter public artifacts or the
# private state dir (only counts and SHA-256 fingerprints do).  Terminal
# output may show the lossless \xNN-escaped display.
param(
    [string]$Model = '',                 # L6 | L19 (required)
    [int]$Seed = 0,                      # L6: 1/2/4, L19: 1
    [int]$Tokens = 32,                   # context window length (8..256; 32 = legacy T32 behavior)
    [int]$Dimension = 32,
    [int]$FeedForwardDimension = 32,
    [string]$Prompt = '',                # arbitrary Japanese text
    [string]$PromptFile = '',            # alternative: raw UTF-8 bytes file
    [int]$MaxNewBytes = 64,              # 1..1024
    [string]$Mode = 'Greedy',            # Greedy | Sample
    [double]$Temperature = 1.0,
    [int]$TopK = 256,
    [uint32]$SamplingSeed = 0,
    [string]$QairtSdkRoot = '',
    [string]$ExpectedBuildId = '',
    [switch]$SkipBuild,
    [switch]$SkipInstall,
    [int]$PollLimit = 600,
    [int]$PollSeconds = 2,
    [int]$ProgressEverySeconds = 30,
    [int]$CheckpointStep = 320,
    [string]$RunId = (Get-Date -Format 'yyyyMMdd-HHmmss-fff'),
    [string]$TrainingReportPath = '',
    [string]$EvalReportPath = '',
    [string]$GatePolicy = 'legacy',   # legacy | candidate | htp-native | htp-smoke
    [switch]$CandidatePolicyApproved, # required to run -GatePolicy candidate
    [switch]$AuditOnly,               # accept a FAILED gate report (audit runs)
    [int]$HtpGraphPrecisionMode = 0,  # private diagnostics: 0 unset, 1 fp16, 2 fp32
    [int]$HtpGraphPrecisionCompensation = 0,  # private diagnostics: 0 unset, 1 false, 2 true
    [int]$HtpGraphWeightsPacking = 0,  # private diagnostics: 0 unset, 1 false, 2 true
    [int]$HtpGraphAdvancedActivationFusion = 0,  # private diagnostics: 0 unset, 1 false, 2 true
    [int]$HtpContextGraphSplitting = 0,  # private diagnostics: 0 unset, 1 false, 2 true
    [switch]$HtpNativeTensorFp16,  # private diagnostics: declare NATIVE tensors FP16
    [switch]$SelfTest
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'qairt_version.ps1')
. (Join-Path $PSScriptRoot 'nicopedia_generation_aggregates.ps1')
. (Join-Path $PSScriptRoot 'nicopedia_runner_common.ps1')
Assert-PhoneLmQairtPinnedArguments -SdkRoot $QairtSdkRoot -ExpectedBuildId $ExpectedBuildId
$root = Split-Path -Parent $PSScriptRoot
$modelTag = if ($Tokens -eq 32 -and $Dimension -eq 32 -and $FeedForwardDimension -eq 32) { '' } else { "-t$Tokens-d$Dimension-f$FeedForwardDimension" }

$reportRoot = Join-Path $root 'build\reports\nicopedia-htp-generation'
$trainingRoot = Join-Path $root 'build\reports\nicopedia-htp-training'
$stateDir = Join-Path $root 'build\private-diagnostics\nicopedia-htp-generation-goal'
[IO.Directory]::CreateDirectory($reportRoot) | Out-Null
[IO.Directory]::CreateDirectory($stateDir) | Out-Null

function Write-Event([string]$Type, [hashtable]$Fields) {
    $entry = @{ ts = [DateTimeOffset]::UtcNow.ToString('o'); type = $Type } + $Fields
    Add-Content -LiteralPath (Join-Path $stateDir 'events.jsonl') `
        -Value ($entry | ConvertTo-Json -Compress) -Encoding utf8
}

function Get-Sha256Hex([string]$LiteralPath) {
    $hash = Get-FileHash -LiteralPath $LiteralPath -Algorithm SHA256
    return $hash.Hash.ToLowerInvariant()
}

function Resolve-PhoneLmHtpNativeAnchorHash {
    param(
        [Parameter(Mandatory = $true)][System.Collections.IDictionary]$EvalHealth,
        [Parameter(Mandatory = $true)][System.Collections.IDictionary]$CpuHealth,
        [AllowNull()][System.Collections.IDictionary]$TrainingHealth
    )
    foreach ($key in @('checkpoint_format', 'checkpoint_finite', 'checkpoint_parameter_hash')) {
        if (-not $EvalHealth.Contains($key)) { throw "HTP_NATIVE_EVAL_ANCHOR_FIELD_MISSING: $key" }
    }
    if ($EvalHealth.checkpoint_format -ne 'NPRTCKPTV2' -or $EvalHealth.checkpoint_finite -ne 'true' -or
        $EvalHealth.checkpoint_parameter_hash -notmatch '^fnv1a64:[0-9a-f]{16}$') {
        throw 'HTP_NATIVE_EVAL_CHECKPOINT_HEALTH_REJECTED'
    }
    foreach ($key in @('parameter_hash', 'finite')) {
        if (-not $CpuHealth.Contains($key)) { throw "HTP_NATIVE_CPU_EVAL_FIELD_MISSING: $key" }
    }
    if ($CpuHealth.parameter_hash -ne $EvalHealth.checkpoint_parameter_hash -or $CpuHealth.finite -ne 'true') {
        throw 'HTP_NATIVE_CPU_EVAL_IDENTITY_REJECTED'
    }
    # A same-step training report is preferred when available.  If the
    # report was lost after a successful run, the full-cap eval + CPU hash
    # pair remains the explicit checkpoint-health anchor for HTP-native mode.
    if ($null -ne $TrainingHealth) {
        if (-not $TrainingHealth.Contains('final_parameter_hash') -or
            $TrainingHealth.final_parameter_hash -ne $EvalHealth.checkpoint_parameter_hash) {
            throw 'HTP_NATIVE_TRAINING_EVAL_HASH_MISMATCH'
        }
    }
    return [string]$EvalHealth.checkpoint_parameter_hash
}

function Assert-PhoneLmHtpSmokeCheckpointHeader {
    param(
        [Parameter(Mandatory = $true)]$Header,
        [Parameter(Mandatory = $true)][int]$Seed,
        [Parameter(Mandatory = $true)][int]$Layers,
        [Parameter(Mandatory = $true)][int]$Tokens,
        [Parameter(Mandatory = $true)][int]$Dimension,
        [Parameter(Mandatory = $true)][int]$FeedForwardDimension,
        [Parameter(Mandatory = $true)][int]$Step
    )
    $expected = [ordered]@{
        Magic = 'NPRTCKPTV2'; Vocabulary = 256; Tokens = $Tokens
        Dimension = $Dimension; FeedForward = $FeedForwardDimension
        Layers = $Layers; Heads = 2; Seed = $Seed; Step = $Step
    }
    foreach ($key in $expected.Keys) {
        if (-not $Header.PSObject.Properties.Name.Contains($key) -or
            $Header.$key -ne $expected[$key]) {
            $actual = if ($Header.PSObject.Properties.Name.Contains($key)) { $Header.$key } else { '<missing>' }
            throw "HTP_SMOKE_CHECKPOINT_HEADER_MISMATCH: $key actual=$actual expected=$($expected[$key])"
        }
    }
}

# Lossless UTF-8 display: valid sequences pass through, invalid/truncated
# bytes become \xNN escapes (lowercase).  Mirrors nicopedia_generation.h.
function Get-SafeUtf8Display([byte[]]$Bytes) {
    $out = [System.Text.StringBuilder]::new()
    $pos = 0
    while ($pos -lt $Bytes.Length) {
        $b = $Bytes[$pos]
        $length = 0
        if ($b -lt 0x80) {
            $length = 1
        } elseif ($b -ge 0xC2 -and $b -le 0xDF) {
            $length = 2
        } elseif ($b -ge 0xE0 -and $b -le 0xEF) {
            $length = 3
        } elseif ($b -ge 0xF0 -and $b -le 0xF4) {
            $length = 4
        }
        $valid = $true
        if ($length -gt 0 -and $pos + $length -le $Bytes.Length) {
            for ($i = 1; $i -lt $length; $i++) {
                $c = $Bytes[$pos + $i]
                if ($c -lt 0x80 -or $c -gt 0xBF) { $valid = $false; break }
            }
            if ($length -eq 3 -and $b -eq 0xE0 -and $Bytes[$pos + 1] -lt 0xA0) { $valid = $false }
            if ($length -eq 3 -and $b -eq 0xED -and $Bytes[$pos + 1] -ge 0xA0) { $valid = $false }
            if ($length -eq 4 -and $b -eq 0xF0 -and $Bytes[$pos + 1] -lt 0x90) { $valid = $false }
            if ($length -eq 4 -and $b -eq 0xF4 -and $Bytes[$pos + 1] -ge 0x90) { $valid = $false }
        } else {
            $valid = $false
        }
        if ($valid) {
            [void]$out.Append([System.Text.Encoding]::UTF8.GetString($Bytes, $pos, $length))
            $pos += $length
        } else {
            [void]$out.Append('\x')
            [void]$out.Append($b.ToString('x2'))
            $pos += 1
        }
    }
    return $out.ToString()
}

function Invoke-SelfTest {
    if ($Tokens -ne 32) { throw "SELFTEST_TOKENS_DEFAULT: expected=32 actual=$Tokens" }

    # Production anchor is T32/D32/FFN32.
    if ($Dimension -ne 32 -or $FeedForwardDimension -ne 32) {
        throw "SELFTEST_MODEL_DIMENSIONS_DEFAULT: expected=T32/D32/FFN32 actual=T$Tokens/D$Dimension/FFN$FeedForwardDimension"
    }

    # Checkpoint naming contract.
    $canonicalD32 = Get-PhoneLmCheckpointName `
        -Seed 1 `
        -Layers 19 `
        -Tokens 32 `
        -Dimension 32 `
        -FeedForwardDimension 32 `
        -Step 8000

    if ($canonicalD32 -ne 'htp-seed1-l19-step8000.ckpt') {
        throw "SELFTEST_D32_CANONICAL_NAME: $canonicalD32"
    }

    $taggedD16 = Get-PhoneLmCheckpointName `
        -Seed 1 `
        -Layers 19 `
        -Tokens 32 `
        -Dimension 16 `
        -FeedForwardDimension 32 `
        -Step 8000

    if ($taggedD16 -ne 'htp-seed1-l19-t32-d16-f32-step8000.ckpt') {
        throw "SELFTEST_D16_TAGGED_NAME: $taggedD16"
    }

    # Safe display mirrors the C++ core (lossless \xNN escapes).
    $cases = @(
        @{ Bytes = [byte[]](0x68, 0x69); Expect = 'hi' },
        @{ Bytes = [byte[]](0xE3, 0x81, 0x93); Expect = [string][char]0x3053 },
        @{ Bytes = [byte[]](0xE3, 0x81); Expect = '\xe3\x81' },
        @{ Bytes = [byte[]](0x61, 0xFF, 0x80, 0x62); Expect = 'a\xff\x80b' },
        @{ Bytes = [byte[]](0xED, 0xA0, 0x80); Expect = '\xed\xa0\x80' }
    )
    foreach ($case in $cases) {
        $actual = Get-SafeUtf8Display -Bytes $case.Bytes
        if ($actual -ne $case.Expect) { throw "SELFTEST_DISPLAY: '$actual' != '$($case.Expect)'" }
    }
    $empty = Get-SafeUtf8Display -Bytes ([byte[]]@())
    if ($empty -ne '') { throw 'SELFTEST_DISPLAY_EMPTY' }

    # CheckpointStep file-name resolution mirrors the shared checkpoint naming
    # contract. T32/D32/FFN32 uses the canonical untagged name; non-anchor
    # configurations such as D16 use explicit -t<T>-d<D>-f<FFN> tags.
    $ckRoot = Join-Path $env:TEMP ("nicopedia-gen-selftest-" + [guid]::NewGuid().ToString('N'))
    [IO.Directory]::CreateDirectory($ckRoot) | Out-Null
    try {
        $step320Name = Get-PhoneLmCheckpointName `
            -Seed 1 `
            -Layers 19 `
            -Tokens 32 `
            -Dimension 32 `
            -FeedForwardDimension 32 `
            -Step 320

        $step1000Name = Get-PhoneLmCheckpointName `
            -Seed 1 `
            -Layers 19 `
            -Tokens 32 `
            -Dimension 32 `
            -FeedForwardDimension 32 `
            -Step 1000
        
        $d16Name = Get-PhoneLmCheckpointName `
            -Seed 1 `
            -Layers 19 `
            -Tokens 32 `
            -Dimension 16 `
            -FeedForwardDimension 32 `
            -Step 1000

        if ($d16Name -ne 'htp-seed1-l19-t32-d16-f32-step1000.ckpt') {
            throw "SELFTEST_D16_CHECKPOINT_NAME: $d16Name"
        }

        $step320Ckpt = Join-Path $ckRoot $step320Name
        $step1000Ckpt = Join-Path $ckRoot $step1000Name
        if ($step320Name -ne 'htp-seed1-l19-step320.ckpt') {
            throw "SELFTEST_CHECKPOINT_NAME_320: $step320Name"
        }

        if ($step1000Name -ne 'htp-seed1-l19-step1000.ckpt') {
            throw "SELFTEST_CHECKPOINT_NAME_1000: $step1000Name"
        }
        [IO.File]::WriteAllText($step320Ckpt, 'selftest-320')
        [IO.File]::WriteAllText($step1000Ckpt, 'selftest-1000')
        $anchor320 = Join-Path $ckRoot 'seed1-l19-steps320-result.txt'
        $anchor1000 = Join-Path $ckRoot 'seed1-l19-steps1000-result.txt'
        [IO.File]::WriteAllText($anchor320, "final_parameter_hash=fnv1a64:0123456789abcdef`n")
        [IO.File]::WriteAllText($anchor1000, "final_parameter_hash=fnv1a64:fedcba9876543210`n")
        # Resolve-* helpers must pick the step-driven file names.
        $checkpoint = Join-Path $ckRoot $step320Name
        $checkpoint1000 = Join-Path $ckRoot $step1000Name
        if (-not (Test-Path -LiteralPath $checkpoint -PathType Leaf) -or
            -not (Test-Path -LiteralPath $anchor320 -PathType Leaf)) {
            throw 'SELFTEST_CHECKPOINT_STEP_320'
        }
        if (-not (Test-Path -LiteralPath $checkpoint1000 -PathType Leaf) -or
            -not (Test-Path -LiteralPath $anchor1000 -PathType Leaf)) {
            throw 'SELFTEST_CHECKPOINT_STEP_1000'
        }
        # A missing step-N file must fail closed.
        foreach ($missing in @(
                (Join-Path $ckRoot 'htp-seed1-l19-step999999.ckpt'),
                (Join-Path $ckRoot 'htp-seed1-l19-step0.ckpt'))) {
            if (Test-Path -LiteralPath $missing -PathType Leaf) {
                throw 'SELFTEST_CHECKPOINT_STEP_LEAK'
            }
        }
    } finally {
        [IO.Directory]::Delete($ckRoot, $true)
    }

    # Aggregate metrics mirror nicopedia_generation.h GenerationAggregates;
    # the shared helper owns both the implementation and its self-test.
    Test-GenerationAggregateSelfTest

    # SHA-256 fingerprint plumbing.
    $temp = Join-Path $env:TEMP ("nicopedia-gen-selftest-" + [guid]::NewGuid().ToString('N'))
    [IO.Directory]::CreateDirectory($temp) | Out-Null
    try {
        $sample = Join-Path $temp 'prompt.bin'
        [IO.File]::WriteAllBytes($sample, [byte[]](0xE3, 0x81, 0x93))
        $h1 = Get-Sha256Hex $sample
        $h2 = Get-Sha256Hex $sample
        if ($h1 -ne $h2 -or $h1.Length -ne 64) { throw 'SELFTEST_SHA256' }
    } finally {
        [IO.Directory]::Delete($temp, $true)
    }

    # CheckpointStep range gate (mirrors the parameter validation).
    foreach ($bad in @(0, -1, 1000000, 9999999)) {
        if ($bad -ge 1 -and $bad -le 999999) { throw "SELFTEST_CHECKPOINT_STEP_RANGE: $bad" }
    }
    if (-not (320 -ge 1 -and 320 -le 999999)) { throw 'SELFTEST_CHECKPOINT_STEP_320_RANGE' }
    if (-not (1000 -ge 1 -and 1000 -le 999999)) { throw 'SELFTEST_CHECKPOINT_STEP_1000_RANGE' }

    # HTP graph precision diagnostic switch range gate (0=unset, 1=fp16, 2=fp32).
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_GRAPH_PRECISION_RANGE: $bad" }
    }
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_GRAPH_PRECISION_COMPENSATION_RANGE: $bad" }
    }
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_GRAPH_WEIGHTS_PACKING_RANGE: $bad" }
    }
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_GRAPH_ACTIVATION_FUSION_RANGE: $bad" }
    }
    foreach ($bad in @(-1, 3, 99)) {
        if ($bad -ge 0 -and $bad -le 2) { throw "SELFTEST_HTP_CONTEXT_GRAPH_SPLITTING_RANGE: $bad" }
    }
    if (-not (0 -ge 0 -and 0 -le 2) -or -not (2 -ge 0 -and 2 -le 2)) {
        throw 'SELFTEST_HTP_GRAPH_PRECISION_VALID_VALUES'
    }
    $fp16Expected = 'false'
    if ($HtpNativeTensorFp16) { $fp16Expected = 'true' }
    if ($fp16Expected -notin @('true', 'false')) {
        throw 'SELFTEST_HTP_NATIVE_TENSOR_FP16_BOOL'
    }
    $evalAnchor = [ordered]@{
        checkpoint_format = 'NPRTCKPTV2'; checkpoint_finite = 'true'
        checkpoint_parameter_hash = 'fnv1a64:0123456789abcdef'
    }
    $cpuAnchor = [ordered]@{
        parameter_hash = 'fnv1a64:0123456789abcdef'; finite = 'true'
    }
    $resolvedWithoutTraining = Resolve-PhoneLmHtpNativeAnchorHash -EvalHealth $evalAnchor -CpuHealth $cpuAnchor -TrainingHealth $null
    if ($resolvedWithoutTraining -ne $evalAnchor.checkpoint_parameter_hash) {
        throw 'SELFTEST_HTP_NATIVE_EVAL_BACKED_ANCHOR'
    }
    $trainingAnchor = [ordered]@{ final_parameter_hash = $evalAnchor.checkpoint_parameter_hash }
    $resolvedWithTraining = Resolve-PhoneLmHtpNativeAnchorHash -EvalHealth $evalAnchor -CpuHealth $cpuAnchor -TrainingHealth $trainingAnchor
    if ($resolvedWithTraining -ne $resolvedWithoutTraining) { throw 'SELFTEST_HTP_NATIVE_TRAINING_ANCHOR' }
    $smokeHeader = [pscustomobject][ordered]@{
        Magic = 'NPRTCKPTV2'; Vocabulary = 256; Tokens = 32; Dimension = 32
        FeedForward = 32; Layers = 19; Heads = 2; Seed = 1; Step = 8000
    }
    Assert-PhoneLmHtpSmokeCheckpointHeader -Header $smokeHeader -Seed 1 -Layers 19 -Tokens 32 -Dimension 32 -FeedForwardDimension 32 -Step 8000
    $smokeHeader.Step = 7999
    try {
        Assert-PhoneLmHtpSmokeCheckpointHeader -Header $smokeHeader -Seed 1 -Layers 19 -Tokens 32 -Dimension 32 -FeedForwardDimension 32 -Step 8000
        throw 'SELFTEST_HTP_SMOKE_HEADER_NEGATIVE'
    } catch {
        if ($_.Exception.Message -notmatch '^HTP_SMOKE_CHECKPOINT_HEADER_MISMATCH:') { throw }
    }
    Write-Host 'run_nicopedia_htp_generate_self_test=PASS'
    exit 0
}

if ($SelfTest) { Invoke-SelfTest }

if ($RunId -notmatch '^[A-Za-z0-9._-]{1,64}$') { throw 'RUN_ID_INVALID' }

if ($Model -ne 'L6' -and $Model -ne 'L19') { throw "MODEL_INVALID: Model must be L6 or L19 (got '$Model')" }
$layers = if ($Model -eq 'L19') { 19 } else { 6 }
if ($Seed -lt 1 -or $Seed -gt 99999) { throw 'SEED_INVALID: Seed must be in 1..99999' }
if ($Tokens -lt 8 -or $Tokens -gt 256) { throw 'TOKENS_INVALID: Tokens must be in 8..256' }
if ($Dimension -lt 2 -or $Dimension -gt 256 -or ($Dimension % 2) -ne 0) { throw 'DIMENSION_INVALID: Dimension must be even and in 2..256' }
if ($FeedForwardDimension -lt 2 -or $FeedForwardDimension -gt 1024) { throw 'FFN_INVALID: FeedForwardDimension must be in 2..1024' }
if ($CheckpointStep -lt 1 -or $CheckpointStep -gt 999999) {
    throw 'CHECKPOINT_STEP_INVALID: CheckpointStep must be in 1..999999'
}
if ($MaxNewBytes -lt 1 -or $MaxNewBytes -gt 1024) { throw 'MAX_NEW_BYTES_INVALID: MaxNewBytes must be in 1..1024' }
if ($Mode -ne 'Greedy' -and $Mode -ne 'Sample') { throw 'MODE_INVALID: Mode must be Greedy or Sample' }
if ($GatePolicy -notin @('legacy', 'candidate', 'htp-native', 'htp-smoke')) {
    throw 'GATE_POLICY_INVALID: GatePolicy must be legacy, candidate, htp-native or htp-smoke'
}
if ($GatePolicy -eq 'candidate' -and -not $CandidatePolicyApproved) {
    throw 'CANDIDATE_POLICY_NOT_APPROVED: -GatePolicy candidate requires -CandidatePolicyApproved (independent Reviewer PASS + explicit instruction)'
}
if ($HtpGraphPrecisionMode -lt 0 -or $HtpGraphPrecisionMode -gt 2) {
    throw 'HTP_GRAPH_PRECISION_MODE_INVALID: must be 0, 1 or 2'
}
if ($HtpGraphPrecisionCompensation -lt 0 -or $HtpGraphPrecisionCompensation -gt 2) {
    throw 'HTP_GRAPH_PRECISION_COMPENSATION_INVALID: must be 0, 1 or 2'
}
if ($HtpGraphWeightsPacking -lt 0 -or $HtpGraphWeightsPacking -gt 2) {
    throw 'HTP_GRAPH_WEIGHTS_PACKING_INVALID: must be 0, 1 or 2'
}
if ($HtpGraphAdvancedActivationFusion -lt 0 -or $HtpGraphAdvancedActivationFusion -gt 2) {
    throw 'HTP_GRAPH_ACTIVATION_FUSION_INVALID: must be 0, 1 or 2'
}
if ($HtpContextGraphSplitting -lt 0 -or $HtpContextGraphSplitting -gt 2) {
    throw 'HTP_CONTEXT_GRAPH_SPLITTING_INVALID: must be 0, 1 or 2'
}
if ($Mode -eq 'Sample') {
    if (-not [double]::IsFinite($Temperature) -or $Temperature -le 0.0) { throw 'TEMPERATURE_INVALID' }
    if ($TopK -lt 1 -or $TopK -gt 256) { throw 'TOPK_INVALID' }
}
if ($Prompt -ne '') {
    $promptBytes = [System.Text.Encoding]::UTF8.GetBytes($Prompt)
} elseif ($PromptFile -ne '') {
    $promptFileFull = [IO.Path]::GetFullPath($PromptFile)
    if (-not (Test-Path -LiteralPath $promptFileFull -PathType Leaf)) { throw "PROMPT_FILE_MISSING: $promptFileFull" }
    $promptBytes = [IO.File]::ReadAllBytes($promptFileFull)
} else {
    throw 'PROMPT_REQUIRED: supply -Prompt or -PromptFile'
}
if ($promptBytes.Length -eq 0) { throw 'PROMPT_EMPTY' }
if ($promptBytes.Length -gt $Tokens) {
    Write-Host "prompt=${Model} seed=$Seed bytes=$($promptBytes.Length) -> device uses last $Tokens bytes (training window semantics)"
}

# Checkpoint + approved anchor (fail-closed before any device work).
# The checkpoint file name embeds the step and, for non-anchor configurations,
# the token window plus D/FFN identity
# (htp-seed<S>-l<L>-t<T>-d<D>-f<FFN>-step<N>.ckpt); the device re-validates
# the full header identity and expected checkpoint_step intent, so a stale or
# mismatched file cannot pass.
$checkpointName = Get-PhoneLmCheckpointName -Seed $Seed -Layers $layers -Tokens $Tokens -Dimension $Dimension -FeedForwardDimension $FeedForwardDimension -Step $CheckpointStep
$checkpoint = Join-Path $trainingRoot $checkpointName
$canonicalTrainingReport = Join-Path $trainingRoot "seed$Seed-l$layers$modelTag-steps$CheckpointStep-result.txt"
if ($GatePolicy -eq 'htp-smoke') {
    if (-not $TrainingReportPath) { $TrainingReportPath = $canonicalTrainingReport }
    if ([IO.Path]::GetFullPath($TrainingReportPath) -ne [IO.Path]::GetFullPath($canonicalTrainingReport)) {
        throw "HTP_SMOKE_TRAINING_REPORT_NOT_CANONICAL: expected=$canonicalTrainingReport"
    }
}
$anchorFile = if ($GatePolicy -eq 'htp-smoke') { $TrainingReportPath } else { $canonicalTrainingReport }
if (-not (Test-Path -LiteralPath $checkpoint -PathType Leaf)) { throw "CHECKPOINT_MISSING: $checkpoint" }
$anchorHash = ''
if ($GatePolicy -eq 'htp-smoke') {
    if (-not (Test-Path -LiteralPath $TrainingReportPath -PathType Leaf)) { throw "ANCHOR_MISSING: $TrainingReportPath" }
    $trainingMap = Get-PhoneLmKeyValueMap -Text (Get-Content -LiteralPath $TrainingReportPath -Raw)
    if (-not $trainingMap.Contains('final_parameter_hash') -or
        $trainingMap.final_parameter_hash -notmatch '^fnv1a64:[0-9a-f]{16}$') {
        throw "HTP_SMOKE_TRAINING_HASH_NOT_FOUND: $TrainingReportPath"
    }
    $anchorHash = [string]$trainingMap.final_parameter_hash
    $checkpointHeader = Get-PhoneLmCheckpointHeaders -Path $checkpoint
    Assert-PhoneLmHtpSmokeCheckpointHeader -Header $checkpointHeader -Seed $Seed -Layers $layers -Tokens $Tokens -Dimension $Dimension -FeedForwardDimension $FeedForwardDimension -Step $CheckpointStep
    Write-Host "htp-smoke prerequisites accepted: canonical training report and NPRTCKPTV2 header verified anchor=$anchorHash"
} elseif ($GatePolicy -ne 'htp-native') {
    if (-not (Test-Path -LiteralPath $anchorFile -PathType Leaf)) { throw "ANCHOR_MISSING: $anchorFile" }
    $anchorText = Get-Content -LiteralPath $anchorFile -Raw
    $anchorMatch = [regex]::Match($anchorText, '(?m)^final_parameter_hash=(fnv1a64:[0-9a-f]{16})$')
    if (-not $anchorMatch.Success) { throw "ANCHOR_HASH_NOT_FOUND: $anchorFile" }
    $anchorHash = $anchorMatch.Groups[1].Value
}

# Experimental HTP-native generation is intentionally downstream of the
# full-cap HTP+CPU held-out reports and, when present, the same-step training
# health report.  If a runner hang lost only the terminal training text, the
# eval/CPU V2 identity pair is the explicit fallback checkpoint anchor.
# Legacy/candidate generation keeps its existing parity behavior unchanged.
if ($GatePolicy -eq 'htp-native') {
    if ($PollLimit -lt 1 -or $PollSeconds -lt 1 -or $ProgressEverySeconds -lt 1) { throw 'POLL_CONFIGURATION_INVALID' }
    if (-not $TrainingReportPath) { $TrainingReportPath = Join-Path $trainingRoot "seed$Seed-l$layers$modelTag-steps$CheckpointStep-result.txt" }
    if (-not $EvalReportPath) { $EvalReportPath = Join-Path $root "build\reports\nicopedia-htp-eval\seed$Seed-l$layers$modelTag-step$CheckpointStep-htp.txt" }
    if (-not (Test-Path -LiteralPath $EvalReportPath -PathType Leaf)) { throw "HTP_NATIVE_EVAL_HEALTH_MISSING: $EvalReportPath" }
    $trainingHealth = $null
    if (Test-Path -LiteralPath $TrainingReportPath -PathType Leaf) {
        $trainingHealth = Assert-PhoneLmHealthReport -Text (Get-Content -LiteralPath $TrainingReportPath -Raw) -ExpectedBuildId $ExpectedBuildId -ExpectedStep $CheckpointStep -Kind training
    } else {
        Write-Host "htp-native training report unavailable; using eval-backed checkpoint health: $TrainingReportPath"
    }
    $evalHealth = Assert-PhoneLmHealthReport -Text (Get-Content -LiteralPath $EvalReportPath -Raw) -ExpectedBuildId $ExpectedBuildId -ExpectedStep $CheckpointStep -Kind eval
    if ($evalHealth.checkpoint_format -ne 'NPRTCKPTV2' -or $evalHealth.checkpoint_finite -ne 'true') {
        throw 'HTP_NATIVE_EVAL_CHECKPOINT_HEALTH_REJECTED'
    }
    $cpuEvalPath = if ($EvalReportPath -match '-htp\.txt$') { $EvalReportPath -replace '-htp\.txt$', '-cpu.txt' } else { [IO.Path]::ChangeExtension($EvalReportPath, 'cpu.txt') }
    if (-not (Test-Path -LiteralPath $cpuEvalPath -PathType Leaf)) { throw "HTP_NATIVE_CPU_EVAL_MISSING: $cpuEvalPath" }
    $cpuHealth = Get-PhoneLmKeyValueMap -Text (Get-Content -LiteralPath $cpuEvalPath -Raw)
    $anchorHash = Resolve-PhoneLmHtpNativeAnchorHash -EvalHealth $evalHealth -CpuHealth $cpuHealth -TrainingHealth $trainingHealth
    $checkpointHeader = Get-PhoneLmCheckpointHeaders -Path $checkpoint
    if ($checkpointHeader.Magic -ne 'NPRTCKPTV2' -or $checkpointHeader.Seed -ne $Seed -or $checkpointHeader.Layers -ne $layers -or $checkpointHeader.Heads -ne 2 -or $checkpointHeader.Tokens -ne $Tokens -or $checkpointHeader.Dimension -ne $Dimension -or $checkpointHeader.FeedForward -ne $FeedForwardDimension -or $checkpointHeader.Step -ne $CheckpointStep) {
        throw 'HTP_NATIVE_CHECKPOINT_IDENTITY_REJECTED'
    }
    $anchorSource = if ($null -ne $trainingHealth) { 'training-report' } else { 'full-cap-eval-cpu' }
    Write-Host "htp-native prerequisites accepted: source=$anchorSource eval/CPU checkpoint health and V2 identity verified"
}

# Fingerprints computed on the host (never the prompt text itself).
$checkpointSha256 = Get-Sha256Hex $checkpoint
$promptSha256Bytes = [System.Security.Cryptography.SHA256]::Create()
$promptSha256 = [System.BitConverter]::ToString($promptSha256Bytes.ComputeHash($promptBytes)).Replace('-', '').ToLowerInvariant()
Write-Event 'host-staged' @{
    model = $Model; seed = $Seed; checkpoint_step = $CheckpointStep
    prompt_byte_count = $promptBytes.Length
    prompt_truncated = ($promptBytes.Length -gt $Tokens); prompt_sha256 = $promptSha256
    checkpoint_sha256 = $checkpointSha256; anchor_hash = $anchorHash
}

$adb = Join-Path $env:LOCALAPPDATA 'Android\Sdk\platform-tools\adb.exe'
$env:ANDROID_HOME = Join-Path $env:LOCALAPPDATA 'Android\Sdk'
$env:ANDROID_SDK_ROOT = $env:ANDROID_HOME
$package = 'com.yuubinnkyoku.phonelm'
$apk = Join-Path $root 'app\build\outputs\apk\debug\app-debug.apk'
$testApk = Join-Path $root 'app\build\outputs\apk\androidTest\debug\app-debug-androidTest.apk'

if (-not $SkipBuild) {
    & (Join-Path $root 'gradlew.bat') :app:assembleDebug :app:assembleDebugAndroidTest '-Pphonelm.enableQnn=true' "-Pqairt.sdkRoot=$QairtSdkRoot" "-Pqairt.expectedBuildId=$ExpectedBuildId" --no-daemon
    if ($LASTEXITCODE -ne 0) { throw 'QNN instrumentation build failed' }
}

$deviceInfo = Resolve-PhoneLmDevice -Adb $adb
$device = $deviceInfo.Endpoint
Assert-PhoneLmPhysicalDevice -Adb $adb -Device $device
Assert-PhoneLmNoExistingRun -Adb $adb -Device $device -Package $package
Assert-PhoneLmNoExistingHeadlessRun -Adb $adb -Device $device -Package $package
$stateBefore = Get-PhoneLmThermalBatteryState -Adb $adb -Device $device -Phase 'before'
$serial = $deviceInfo.Serial
$modelName = $deviceInfo.Model
$soc = $deviceInfo.Soc

function Adb([string[]]$Arguments) {
    return (Invoke-PhoneLmAdb -Adb $adb -Device $device -Arguments $Arguments).Output
}

if (-not $SkipInstall) {
    if (-not (Test-Path -LiteralPath $apk -PathType Leaf) -or -not (Test-Path -LiteralPath $testApk -PathType Leaf)) { throw 'APK_OR_TEST_APK_MISSING' }
    Adb @('install', '-r', $apk) | Out-Null
    Adb @('install', '-r', '-t', $testApk) | Out-Null
    Adb @('shell', 'am', 'force-stop', $package) | Out-Null
    Assert-PhoneLmNoExistingRun -Adb $adb -Device $device -Package $package
}
Assert-PhoneLmInstalledApkMatches -Adb $adb -Device $device -Package $package -LocalApk $apk
Assert-PhoneLmInstalledApkMatches -Adb $adb -Device $device -Package "$package.test" -LocalApk $testApk

# Stage checkpoint + prompt under the run-scoped headless input directory.
$remoteDir = "files/headless-input/$RunId"
Assert-PhoneLmHeadlessInputFresh -Adb $adb -Device $device -Package $package -RemoteDir $remoteDir
Adb @('shell', 'run-as', $package, 'mkdir', '-p', $remoteDir) | Out-Null
$tmpCheckpoint = "/data/local/tmp/phonelm-headless-$RunId-checkpoint"
$tmpPrompt = "/data/local/tmp/phonelm-headless-$RunId-prompt.bin"
$localPrompt = Join-Path $env:TEMP ("nicopedia-prompt-" + [guid]::NewGuid().ToString('N') + '.bin')
try {
    [IO.File]::WriteAllBytes($localPrompt, $promptBytes)
Adb @('push', $checkpoint, $tmpCheckpoint) | Out-Null
Adb @('push', $localPrompt, $tmpPrompt) | Out-Null
} finally {
    Remove-Item -LiteralPath $localPrompt -Force -ErrorAction SilentlyContinue
}
Adb @('shell', 'run-as', $package, 'cp', $tmpCheckpoint, "$remoteDir/$checkpointName") | Out-Null
Adb @('shell', 'run-as', $package, 'cp', $tmpPrompt, "$remoteDir/prompt.bin") | Out-Null
Adb @('shell', 'rm', '-f', $tmpCheckpoint, $tmpPrompt) | Out-Null

# Drive generation through the headless instrumentation suite.  The preflight
# above ensures no prior process/result exists; lifecycle remains headless.
Clear-PhoneLmResultMarker -Adb $adb -Device $device -Package $package
$instrumentDir = Join-Path $reportRoot "instrumentation-$RunId"
if (Test-Path -LiteralPath $instrumentDir) { throw 'RUN_ID_REUSE: host instrumentation directory exists' }
[IO.Directory]::CreateDirectory($instrumentDir) | Out-Null
$instrument = $null
try {
  $instrument = Start-PhoneLmHeadlessInstrumentation -Adb $adb -Device $device -Package $package `
    -Class "$package.HeadlessDeviceTestRunner" -Suite 'nicopedia-generate' -RunId $RunId `
    -Arguments @{ seed = $Seed; layers = $layers; tokens = $Tokens; dimension = $Dimension; feedForwardDimension = $FeedForwardDimension; checkpointStep = $CheckpointStep; generateMode = $Mode.ToLowerInvariant(); maxNewBytes = $MaxNewBytes; temperature = $Temperature.ToString([System.Globalization.CultureInfo]::InvariantCulture); topK = $TopK; samplingSeed = $SamplingSeed; gatePolicy = $GatePolicy } `
    -StdoutPath (Join-Path $instrumentDir 'stdout.txt') -StderrPath (Join-Path $instrumentDir 'stderr.txt')
$waited = Wait-PhoneLmHeadlessStatus -Process $instrument -Adb $adb -Device $device -Package $package `
    -PollLimit $PollLimit -PollSeconds $PollSeconds -ProgressEverySeconds $ProgressEverySeconds -Label "generation-step-$CheckpointStep" `
    -ExpectedRunId $RunId `
    -PartialPath (Join-Path $reportRoot "seed$Seed-l$layers-$($Mode.ToLowerInvariant())-step$CheckpointStep-partial-status.json") `
    -StatusProgressAction {
        param($elapsed, $status)
        $phase = [regex]::Match($status, '"current_phase"\s*:\s*"([^"]*)"').Groups[1].Value
        Write-Host "progress phase=generation elapsed_seconds=$elapsed status_phase=$phase"
    } `
    -ConditionAction {
        param($elapsed)
        $state = Get-PhoneLmThermalBatteryState -Adb $adb -Device $device -Phase "generation-$elapsed-sec"
        Write-Host "health elapsed_seconds=$elapsed thermal=$($state.thermal_status) battery_temp_c=$($state.battery_temperature_c) battery_voltage_mv=$($state.battery_voltage_mv)"
    } `
    -FocusAction {
        param($elapsed)
        if ((Get-PhoneLmTopPackage -Adb $adb -Device $device) -eq $package) { throw 'FOCUS_TAKEOVER_DETECTED' }
    }
$result = Get-PhoneLmHeadlessReport -StatusJson $waited.StatusJson -Adb $adb -Device $device -Package $package
if ($waited.ProcessExitCode -ne 0 -and -not $AuditOnly) { throw "INSTRUMENTATION_EXIT_FAILURE: code=$($waited.ProcessExitCode)" }
Assert-PhoneLmHeadlessNoActivity -Text $result
if ($result -notmatch 'NICOPEDIA_HTP_GENERATION') {
    $preview = if ($result.Length -gt 4096) {
        $result.Substring(0, 4096)
    } else {
        $result
    }
    throw "DEVICE_RESULT_SCHEMA_MISMATCH: expected=NICOPEDIA_HTP_GENERATION`nactual:`n$preview"
}
if ($result -notmatch '(?m)^status=SUCCESS$') {
    if (-not $AuditOnly) {
        throw "DEVICE_GENERATION_FAILED:`n$result"
    }
    Write-Host 'AUDIT_ONLY: device status != SUCCESS — parity metrics recorded'
}
if ($result -notmatch '(?m)^cpu_fallback=false$') { throw 'DEVICE_CPU_FALLBACK_DETECTED' }
$deviceDimensionMatch = [regex]::Match($result, '(?m)^model_dimension=(\d+)$')
$deviceFfnMatch = [regex]::Match($result, '(?m)^feed_forward_dimension=(\d+)$')
if (-not $deviceDimensionMatch.Success -or -not $deviceFfnMatch.Success -or
    [int]$deviceDimensionMatch.Groups[1].Value -ne $Dimension -or
    [int]$deviceFfnMatch.Groups[1].Value -ne $FeedForwardDimension) {
    throw 'DEVICE_MODEL_IDENTITY_MISMATCH'
}
$deviceHashMatch = [regex]::Match($result, '(?m)^checkpoint_parameter_hash=(fnv1a64:[0-9a-f]{16})$')
if (-not $deviceHashMatch.Success) { throw 'DEVICE_PARAMETER_HASH_MISSING' }
if ($deviceHashMatch.Groups[1].Value -ne $anchorHash) {
    throw "CHECKPOINT_IDENTITY_MISMATCH: device=$($deviceHashMatch.Groups[1].Value) anchor=$anchorHash"
}
# The device re-validates the expected step (nprtParseCheckpointStep +
# loaded.step != expectedStep).  Mirror that contract on the host so a
# mismatched checkpoint_step intent cannot slip through a stale report.
$headerStepMatch = [regex]::Match($result, '(?m)^checkpoint_header_step=(\d+)$')
if (-not $headerStepMatch.Success) { throw 'DEVICE_HEADER_STEP_MISSING' }
if ([int]$headerStepMatch.Groups[1].Value -ne $CheckpointStep) {
    throw "CHECKPOINT_STEP_MISMATCH: header=$($headerStepMatch.Groups[1].Value) expected=$CheckpointStep"
}
$parityGate = [regex]::Match($result, '(?m)^parity_gate=(true|false)$').Groups[1].Value
$arGate = [regex]::Match($result, '(?m)^ar_gate=(true|false)$').Groups[1].Value
$generationGate = [regex]::Match($result, '(?m)^generation_gate=(true|false)$').Groups[1].Value
$parityGateCandidate = [regex]::Match($result, '(?m)^parity_gate_candidate=(true|false)$').Groups[1].Value
$arGateCandidate = [regex]::Match($result, '(?m)^ar_gate_candidate=(true|false)$').Groups[1].Value
$gatePolicyReported = [regex]::Match($result, '(?m)^gate_policy=(legacy|candidate|htp-native|htp-smoke)$').Groups[1].Value
if ($gatePolicyReported -ne $GatePolicy) {
    throw "GATE_POLICY_MISMATCH: device=$gatePolicyReported requested=$GatePolicy"
}
$precisionModeReported = [regex]::Match($result, '(?m)^htp_graph_precision_mode=(\d+)$').Groups[1].Value
$precisionCompensationReported = [regex]::Match($result, '(?m)^htp_graph_precision_compensation=(\d+)$').Groups[1].Value
$weightsPackingReported = [regex]::Match($result, '(?m)^htp_graph_weights_packing=(\d+)$').Groups[1].Value
$fusionReported = [regex]::Match($result, '(?m)^htp_graph_activation_fusion=(\d+)$').Groups[1].Value
$graphSplittingReported = [regex]::Match($result, '(?m)^htp_context_graph_splitting=(\d+)$').Groups[1].Value
$graphSplittingDelivery = [regex]::Match($result, '(?m)^htp_context_graph_splitting_delivery=(unset_nullptr|passed_to_qnn_context_create)$').Groups[1].Value
$executionFingerprint = [regex]::Match($result, '(?m)^htp_execution_fingerprint_sha256=([0-9a-f]{64})$').Groups[1].Value
$nativeFp16Reported = [regex]::Match($result, '(?m)^htp_native_tensor_fp16=(true|false)$').Groups[1].Value
if ($precisionModeReported -eq '' -or $precisionCompensationReported -eq '' -or
    $weightsPackingReported -eq '' -or $fusionReported -eq '' -or $graphSplittingReported -eq '' -or
    $graphSplittingDelivery -eq '' -or $executionFingerprint -eq '' -or $nativeFp16Reported -eq '') {
    throw 'HTP_GRAPH_PRECISION_FIELDS_MISSING: report lacks htp_graph_precision fields'
}
$nativeFp16Expected = 'false'
if ($HtpNativeTensorFp16) { $nativeFp16Expected = 'true' }
if ([int]$precisionModeReported -ne $HtpGraphPrecisionMode -or
    [int]$precisionCompensationReported -ne $HtpGraphPrecisionCompensation -or
    [int]$weightsPackingReported -ne $HtpGraphWeightsPacking -or
    [int]$fusionReported -ne $HtpGraphAdvancedActivationFusion -or
    [int]$graphSplittingReported -ne $HtpContextGraphSplitting -or
    $nativeFp16Reported -ne $nativeFp16Expected) {
    throw "HTP_GRAPH_PRECISION_MISMATCH: device=($precisionModeReported,$precisionCompensationReported,$weightsPackingReported,$fusionReported,$graphSplittingReported,$nativeFp16Reported) requested=($HtpGraphPrecisionMode,$HtpGraphPrecisionCompensation,$HtpGraphWeightsPacking,$HtpGraphAdvancedActivationFusion,$HtpContextGraphSplitting,$nativeFp16Expected)"
}
$graphSplittingDeliveryExpected = if ($HtpContextGraphSplitting -eq 0) { 'unset_nullptr' } else { 'passed_to_qnn_context_create' }
if ($graphSplittingDelivery -ne $graphSplittingDeliveryExpected) {
    throw "HTP_CONTEXT_GRAPH_SPLITTING_DELIVERY_MISMATCH: device=$graphSplittingDelivery requested=$HtpContextGraphSplitting expected=$graphSplittingDeliveryExpected"
}
if ($parityGateCandidate -eq '' -or $arGateCandidate -eq '') {
    throw 'CANDIDATE_GATE_FIELDS_MISSING: report lacks parity_gate_candidate/ar_gate_candidate'
}

if ($GatePolicy -eq 'htp-native' -or $GatePolicy -eq 'htp-smoke') {
    # HTP-native execution is health-gated independently of legacy parity.
    # The trace and every reported finite row are mandatory evidence; missing
    # fields fail closed instead of being interpreted as a success.
    $generationHealthMap = Assert-PhoneLmHealthReport -Text $result -ExpectedBuildId $ExpectedBuildId -ExpectedStep $CheckpointStep -Kind generation
    if (-not $generationHealthMap.Contains('checkpoint_finite') -or $generationHealthMap.checkpoint_finite -ne 'true' -or
        -not $generationHealthMap.Contains('generation_health') -or $generationHealthMap.generation_health -ne 'true') {
        throw 'GENERATION_HEALTH_REJECTED'
    }
    $parityFinite = @([regex]::Matches($result, '(?m)^parity_\d+_finite=(true|false)$'))
    $arFinite = @([regex]::Matches($result, '(?m)^ar_step_\d+_finite=(true|false)$'))
    $probabilityFields = @([regex]::Matches($result, '(?m)^parity_\d+_probability_(?:max_abs_error|mean_abs_error)=([^\s]+)$'))
    if ($parityFinite.Count -eq 0 -or $arFinite.Count -eq 0) { throw 'GENERATION_FINITE_FIELDS_MISSING' }
    if (@($parityFinite | Where-Object { $_.Groups[1].Value -ne 'true' }).Count -gt 0 -or @($arFinite | Where-Object { $_.Groups[1].Value -ne 'true' }).Count -gt 0) { throw 'GENERATION_FINITE_REJECTED' }
    if ($probabilityFields.Count -eq 0 -or @($probabilityFields | Where-Object { $_.Groups[1].Value -match '(?i)nan|inf' }).Count -gt 0) { throw 'GENERATION_PROBABILITY_FIELDS_REJECTED' }
    if (-not $result.Contains('generated_valid_utf8_bytes=') -or -not $result.Contains('generated_invalid_utf8_bytes=')) { throw 'GENERATION_PROBABILITY_OR_UTF8_FIELDS_MISSING' }
    # The explicit experimental policy: generation is gated on HTP health
    # alone (fail-closed at every graph execute on-device); the parity rows
    # stay in the report as diagnostics and never block the run.
    if ($GatePolicy -eq 'htp-smoke') {
        $smokeOnlyReported = [regex]::Match($result, '(?m)^smoke_only=(true|false)$').Groups[1].Value
        if ($smokeOnlyReported -ne 'true') { throw 'HTP_SMOKE_REPORT_NOT_MARKED_SMOKE_ONLY' }
        $smokeHeaders = [ordered]@{
            checkpoint_header_vocabulary = '256'; checkpoint_header_tokens = [string]$Tokens
            checkpoint_header_dimension = [string]$Dimension; checkpoint_header_feedforward = [string]$FeedForwardDimension
            checkpoint_header_layers = [string]$layers; checkpoint_header_heads = '2'
            checkpoint_header_seed = [string]$Seed; checkpoint_header_step = [string]$CheckpointStep
            checkpoint_format = 'NPRTCKPTV2'
            checkpoint_finite = 'true'; htp_native_prefix_logits_finite = 'true'
            htp_native_prefix_probabilities_finite = 'true'; htp_native_ar_logits_finite = 'true'
            htp_native_ar_probabilities_finite = 'true'; htp_native_generation_logits_finite = 'true'
            htp_native_generation_probabilities_finite = 'true'
        }
        $smokeMap = Get-PhoneLmKeyValueMap -Text $result
        foreach ($entry in $smokeHeaders.GetEnumerator()) {
            if (-not $smokeMap.Contains($entry.Key) -or $smokeMap[$entry.Key] -ne $entry.Value) {
                throw "HTP_SMOKE_REPORT_FIELD_REJECTED: $($entry.Key)"
            }
        }
    }
    if ($generationGate -ne 'true') {
        if ($GatePolicy -eq 'htp-native') {
            throw "HTP_NATIVE_GENERATION_GATE_REJECTED generation=$generationGate`n$result"
        }
        throw "HTP_SMOKE_GENERATION_GATE_REJECTED generation=$generationGate`n$result"
    }
    if ($GatePolicy -eq 'htp-native') {
        Write-Host "htp-native policy accepted; parity diagnostics: parity=$parityGate ar=$arGate"
    } else {
        Write-Host "htp-smoke policy accepted; parity diagnostics: parity=$parityGate ar=$arGate"
    }
} else {
    if ($parityGate -ne 'true' -or $arGate -ne 'true' -or $generationGate -ne 'true') {
        if (-not $AuditOnly) {
            throw "GENERATION_GATE_REJECTED parity=$parityGate ar=$arGate generation=$generationGate`n$result"
        }
        Write-Host "AUDIT_ONLY: gate rejected (parity=$parityGate ar=$arGate generation=$generationGate) — parity metrics recorded"
    }
}
$generatedHex = [regex]::Match($result, '(?m)^generated_hex=([0-9a-f]*)$').Groups[1].Value
$generatedBytes = [byte[]]@()
if ($generatedHex.Length -gt 0) {
    $generatedBytes = [byte[]]::new($generatedHex.Length / 2)
    for ($i = 0; $i -lt $generatedHex.Length; $i += 2) {
        $generatedBytes[$i / 2] = [Convert]::ToByte($generatedHex.Substring($i, 2), 16)
    }
}
if (-not $AuditOnly) {
    if ($generatedBytes.Length -ne $MaxNewBytes) {
        throw "GENERATED_BYTE_COUNT_MISMATCH: expected=$MaxNewBytes actual=$($generatedBytes.Length)"
    }
}
$generatedSha256Bytes = [System.Security.Cryptography.SHA256]::Create()
$generatedSha256 = [System.BitConverter]::ToString($generatedSha256Bytes.ComputeHash($generatedBytes)).Replace('-', '').ToLowerInvariant()
$generatedStats = Get-SafeUtf8Display -Bytes $generatedBytes

$stateAfter = Get-PhoneLmThermalBatteryState -Adb $adb -Device $device -Phase 'after'

$annotated = $result.TrimEnd() + "`n" +
    "host_prompt_sha256=$promptSha256`n" +
    "host_generated_sha256=$generatedSha256`n" +
    "host_checkpoint_sha256=$checkpointSha256`n" +
    "host_anchor_hash=$anchorHash`n" +
    "device_model=$modelName`n" +
    "device_soc=$soc`n" +
    "android_thermal_status_before=$($stateBefore.thermal_status)`n" +
    "android_thermal_status_after=$($stateAfter.thermal_status)`n" +
    "battery_health_before=$($stateBefore.battery_health)`n" +
    "battery_health_after=$($stateAfter.battery_health)`n" +
    "battery_present_before=$($stateBefore.battery_present.ToString().ToLowerInvariant())`n" +
    "battery_present_after=$($stateAfter.battery_present.ToString().ToLowerInvariant())`n" +
    "battery_level_before=$($stateBefore.battery_level)`n" +
    "battery_level_after=$($stateAfter.battery_level)`n" +
    "battery_voltage_mv_before=$($stateBefore.battery_voltage_mv)`n" +
    "battery_voltage_mv_after=$($stateAfter.battery_voltage_mv)`n" +
    "battery_temperature_c_before=$($stateBefore.battery_temperature_c)`n" +
    "battery_temperature_c_after=$($stateAfter.battery_temperature_c)`n" +
    "compile_time_qairt_build_id=$ExpectedBuildId`n" +
    "host_htp_graph_precision_mode=$HtpGraphPrecisionMode`n" +
    "host_htp_graph_precision_compensation=$HtpGraphPrecisionCompensation`n" +
    "host_htp_graph_weights_packing=$HtpGraphWeightsPacking`n" +
    "host_htp_graph_activation_fusion=$HtpGraphAdvancedActivationFusion`n" +
    "host_htp_context_graph_splitting=$HtpContextGraphSplitting`n" +
    "host_htp_native_tensor_fp16=$nativeFp16Expected`n" +
    "private_serial_recorded_for_identity_only=true`n"
$canonicalReportFile = Join-Path $reportRoot "seed$Seed-l$layers$modelTag-$($Mode.ToLowerInvariant())-step$CheckpointStep-max$MaxNewBytes-result.txt"
# Keep the legacy canonical name for aggregate exporters, but also preserve a
# run-scoped private copy so multiple prompts with the same numeric config do
# not destroy one another's raw evidence.  The `.private.txt` suffix is
# intentionally outside the public exporter's `*result.txt` input glob.
$reportFile = Join-Path $reportRoot "seed$Seed-l$layers-$($Mode.ToLowerInvariant())-step$CheckpointStep-max$MaxNewBytes-$RunId.private.txt"
$annotated | Set-Content -LiteralPath $canonicalReportFile -Encoding utf8
$annotated | Set-Content -LiteralPath $reportFile -Encoding utf8
$annotated | Add-Content -LiteralPath (Join-Path $reportRoot 'device-identity-private.txt') -Encoding utf8

Write-Event 'device-generation-succeeded' @{
    model = $Model; seed = $Seed; mode = $Mode.ToLowerInvariant()
    temperature = $Temperature; top_k = $TopK; sampling_seed = $SamplingSeed
    max_new_bytes = $MaxNewBytes
    generated_byte_count = $generatedBytes.Length
    parity_gate = $parityGate; ar_gate = $arGate; generation_gate = $generationGate
    parity_gate_candidate = $parityGateCandidate; ar_gate_candidate = $arGateCandidate
    gate_policy = $gatePolicyReported
}

# Aggregate-only state (no prompt text, no generated bytes, no serials).
$state = [ordered]@{
    schema = 'nicopedia-htp-generation-goal-v1'
    updated_utc = [DateTimeOffset]::UtcNow.ToString('o')
    last_run = [ordered]@{
        model = $Model; seed = $Seed; layers = $layers
        checkpoint_step = $CheckpointStep
        mode = $Mode.ToLowerInvariant(); temperature = $Temperature
        top_k = $TopK; sampling_seed = $SamplingSeed
        max_new_bytes = $MaxNewBytes
        generated_byte_count = $generatedBytes.Length
        generated_invalid_utf8_bytes = ([regex]::Match($result, '(?m)^generated_invalid_utf8_bytes=(\d+)$').Groups[1].Value -as [int])
        parity_gate = $parityGate; ar_gate = $arGate; generation_gate = $generationGate
        parity_gate_candidate = $parityGateCandidate; ar_gate_candidate = $arGateCandidate
        gate_policy = $gatePolicyReported
    }
    run_count = (Get-Content -LiteralPath (Join-Path $stateDir 'events.jsonl') -ErrorAction SilentlyContinue | Measure-Object).Count
}
[IO.File]::WriteAllText((Join-Path $stateDir 'state.json'),
    ($state | ConvertTo-Json -Depth 6) + "`n", [Text.UTF8Encoding]::new($false))

Write-Host ''
Write-Host "== Nicopedia HTP generation ($Model seed=$Seed) =="
Write-Host "prompt (lossless): $Prompt"
if ($PromptFile -ne '') { Write-Host "prompt file: $PromptFile" }
Write-Host "prompt bytes: $($promptBytes.Length) (context: last $Tokens, device-validated)"
Write-Host "mode=$Mode temp=$Temperature topK=$TopK samplingSeed=$SamplingSeed maxNewBytes=$MaxNewBytes checkpointStep=$CheckpointStep"
Write-Host "parity_gate=$parityGate ar_gate=$arGate generation_gate=$generationGate"
Write-Host "generated bytes: $($generatedBytes.Length)"
Write-Host "generated (lossless display): $generatedStats"
Write-Host "generated_sha256=$generatedSha256"
Write-Host "checkpoint_parameter_hash=$($deviceHashMatch.Groups[1].Value) (anchor match)"
Write-Host "PASS NICOPEDIA_HTP_GENERATION seed=$Seed layers=$layers mode=$($Mode.ToLowerInvariant()) bytes=$($generatedBytes.Length)"
Write-Host "Report: $reportFile"
} finally {
    [void](Stop-PhoneLmCompletedHeadlessProcesses -Adb $adb -Device $device -Package $package -ExpectedRunId $RunId)
    Stop-PhoneLmOwnedInstrumentation -Process $instrument
}
