// SPDX-License-Identifier: Apache-2.0
// Auto-generated by export_transformer_parameter_metadata. DO NOT EDIT.
package com.yuubinnkyoku.phonelm

enum class GeneratedParameterRole { MUON, AUX_ADAM }
enum class GeneratedParameterPlacement { GLOBAL_PREFIX, PER_LAYER, GLOBAL_SUFFIX }
enum class GeneratedParameterCondition { ALWAYS, HEADWISE_G1 }
enum class GeneratedParameterDimension { VOCABULARY, MODEL, FEED_FORWARD, HEADS }

data class GeneratedParameterDefinition(
    val suffix: String,
    val role: GeneratedParameterRole,
    val placement: GeneratedParameterPlacement,
    val condition: GeneratedParameterCondition,
    val shape: List<GeneratedParameterDimension>,
    val rank: Int,
    val fanOutAxis: Int,
    val fanInAxis: Int,
)

object GeneratedTransformerParameterMetadata {
    const val SCHEMA_VERSION: Int = 1

    val DEFINITIONS: List<GeneratedParameterDefinition> = listOf(
        GeneratedParameterDefinition(
            suffix = "token_embedding",
            role = GeneratedParameterRole.AUX_ADAM,
            placement = GeneratedParameterPlacement.GLOBAL_PREFIX,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.VOCABULARY, GeneratedParameterDimension.MODEL),
            rank = 2,
            fanOutAxis = -1,
            fanInAxis = -1,
        ),
        GeneratedParameterDefinition(
            suffix = "norm1_gamma",
            role = GeneratedParameterRole.AUX_ADAM,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL),
            rank = 1,
            fanOutAxis = -1,
            fanInAxis = -1,
        ),
        GeneratedParameterDefinition(
            suffix = "norm1_beta",
            role = GeneratedParameterRole.AUX_ADAM,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL),
            rank = 1,
            fanOutAxis = -1,
            fanInAxis = -1,
        ),
        GeneratedParameterDefinition(
            suffix = "wq",
            role = GeneratedParameterRole.MUON,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL, GeneratedParameterDimension.MODEL),
            rank = 2,
            fanOutAxis = 1,
            fanInAxis = 0,
        ),
        GeneratedParameterDefinition(
            suffix = "wk",
            role = GeneratedParameterRole.MUON,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL, GeneratedParameterDimension.MODEL),
            rank = 2,
            fanOutAxis = 1,
            fanInAxis = 0,
        ),
        GeneratedParameterDefinition(
            suffix = "wv",
            role = GeneratedParameterRole.MUON,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL, GeneratedParameterDimension.MODEL),
            rank = 2,
            fanOutAxis = 1,
            fanInAxis = 0,
        ),
        GeneratedParameterDefinition(
            suffix = "wo",
            role = GeneratedParameterRole.MUON,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL, GeneratedParameterDimension.MODEL),
            rank = 2,
            fanOutAxis = 1,
            fanInAxis = 0,
        ),
        GeneratedParameterDefinition(
            suffix = "attention_gate_weight",
            role = GeneratedParameterRole.AUX_ADAM,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.HEADWISE_G1,
            shape = listOf(GeneratedParameterDimension.MODEL, GeneratedParameterDimension.HEADS),
            rank = 2,
            fanOutAxis = -1,
            fanInAxis = -1,
        ),
        GeneratedParameterDefinition(
            suffix = "norm2_gamma",
            role = GeneratedParameterRole.AUX_ADAM,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL),
            rank = 1,
            fanOutAxis = -1,
            fanInAxis = -1,
        ),
        GeneratedParameterDefinition(
            suffix = "norm2_beta",
            role = GeneratedParameterRole.AUX_ADAM,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL),
            rank = 1,
            fanOutAxis = -1,
            fanInAxis = -1,
        ),
        GeneratedParameterDefinition(
            suffix = "ffn_w1",
            role = GeneratedParameterRole.MUON,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL, GeneratedParameterDimension.FEED_FORWARD),
            rank = 2,
            fanOutAxis = 1,
            fanInAxis = 0,
        ),
        GeneratedParameterDefinition(
            suffix = "ffn_w2",
            role = GeneratedParameterRole.MUON,
            placement = GeneratedParameterPlacement.PER_LAYER,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.FEED_FORWARD, GeneratedParameterDimension.MODEL),
            rank = 2,
            fanOutAxis = 1,
            fanInAxis = 0,
        ),
        GeneratedParameterDefinition(
            suffix = "output_projection",
            role = GeneratedParameterRole.AUX_ADAM,
            placement = GeneratedParameterPlacement.GLOBAL_SUFFIX,
            condition = GeneratedParameterCondition.ALWAYS,
            shape = listOf(GeneratedParameterDimension.MODEL, GeneratedParameterDimension.VOCABULARY),
            rank = 2,
            fanOutAxis = -1,
            fanInAxis = -1,
        )
    )

    fun calculateParameterCount(
        vocabularySize: Long,
        dimension: Long,
        feedForwardDimension: Long,
        layers: Long,
        heads: Long,
        headwiseG1: Boolean = false,
    ): Long {
        var total = 0L
        for (def in DEFINITIONS) {
            if (def.condition == GeneratedParameterCondition.HEADWISE_G1 && !headwiseG1) continue
            var elements = 1L
            for (dim in def.shape) {
                val extent = when (dim) {
                    GeneratedParameterDimension.VOCABULARY -> vocabularySize
                    GeneratedParameterDimension.MODEL -> dimension
                    GeneratedParameterDimension.FEED_FORWARD -> feedForwardDimension
                    GeneratedParameterDimension.HEADS -> heads
                }
                elements = Math.multiplyExact(elements, extent)
            }
            val instances = when (def.placement) {
                GeneratedParameterPlacement.PER_LAYER -> layers
                GeneratedParameterPlacement.GLOBAL_PREFIX, GeneratedParameterPlacement.GLOBAL_SUFFIX -> 1L
            }
            total = Math.addExact(total, Math.multiplyExact(elements, instances))
        }
        return total
    }
}
