// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 yuubinnkyoku
#pragma once
// Shared, host-testable core for Nicopedia byte-level generation.
//
// This header has no QNN / Android / MNN dependencies: the same sources are
// compiled into the device runtime (qnn/qnn_transformer_training.cpp) and into
// the CI-safe host test (host_tests/nicopedia_htp_generation_test.cpp).
//
// Contracts (fixed by the HTP training milestone):
//  - The model predicts the byte after a rolling 32-byte window (T=32,
//    V=256: every byte value is a token, no EOS).  Generation stops only at
//    maxNewBytes.
//  - Context windows are the LAST `tokens` bytes of history; shorter
//    histories are NUL-padded at the front (documented edge-case contract,
//    training windows are always full 32-byte chunks).
//  - Display is lossless: valid UTF-8 passes through, every invalid or
//    truncated byte is emitted as a literal \xNN escape; bytes are never
//    silently dropped or replaced.
//  - Sampling is deterministic within a platform for (seed, step): splitmix64
//    state, fp64 softmax over the temperature-scaled top-K logits, inverse
//    CDF draw.  Cross-platform bit-exact sampling is NOT claimed (libm exp
//    may differ in the last ulp).

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>

namespace phonelm::nicopedia_gen {

struct GenerateConfig {
  uint32_t maxNewBytes = 64;
  bool greedy = true;
  float temperature = 1.0f;
  // 1..256; values above the vocabulary are clamped to the vocabulary.
  uint32_t topK = 256;
  uint64_t samplingSeed = 0;
};

struct Utf8Stats {
  size_t validBytes = 0;
  size_t invalidBytes = 0;
  size_t escapeSpans = 0;  // number of \xNN escapes emitted
};

// Lossless display form (see header comment).  `stats` receives the byte
// statistics of the input (valid/invalid counts, escape spans).
std::string safeUtf8Display(const std::vector<uint8_t>& bytes,
                            Utf8Stats* stats = nullptr);

// Byte statistics without building the display string.
Utf8Stats utf8StatsOf(const std::vector<uint8_t>& bytes);

// Rolling context window per the training contract.  Returns the last
// `tokens` bytes right-aligned; a shorter history is NUL-padded at the front
// and the padding count is written to `padBytes` (nullable).  An empty
// history yields `tokens` NUL bytes (padding == tokens).
std::vector<uint8_t> buildGenerationContext(const std::vector<uint8_t>& history,
                                            uint32_t tokens,
                                            uint32_t* padBytes = nullptr);

// Deterministic argmax over a logits row (first maximum on ties).
uint8_t greedyArgmax(const float* logits, uint32_t vocab);

// Deterministic temperature + top-K sampling (see header comment).
// `topK == 0` means the full vocabulary; a non-positive or non-finite
// temperature falls back to greedy argmax.
uint8_t sampleTopK(const float* logits, uint32_t vocab, float temperature,
                   uint32_t topK, uint64_t seed, uint64_t step);

std::string bytesToHex(const std::vector<uint8_t>& bytes);

// Parses lowercase hex; throws std::invalid_argument on malformed input.
std::vector<uint8_t> hexToBytes(const std::string& hex);

// Slide the rolling window: append one generated byte, drop the oldest.
inline void appendByteWindow(std::vector<uint8_t>& window, uint8_t byte) {
  window.erase(window.begin());
  window.push_back(byte);
}

// Fixed synthetic parity prefixes (deterministic; no licensed corpus text).
// These exact byte sequences are compiled into both the device run and the
// host test so CPU/HTP parity is measured on identical inputs.
struct ParityPrefix {
  const char* label;
  std::vector<uint8_t> bytes;
};
const std::vector<ParityPrefix>& parityPrefixes();

// ---------------------------------------------------------------------------
// Implementation (header-only: compiled into the device and the host test).
// ---------------------------------------------------------------------------

namespace detail {

inline bool isContinuation(uint8_t b) { return (b & 0xc0u) == 0x80u; }

// Returns the expected total sequence length when `b` is a lead byte, or 0
// when the lead byte is invalid.
inline uint32_t leadLength(uint8_t b) {
  if (b < 0x80u) return 1;
  if (b >= 0xc2u && b <= 0xdfu) return 2;
  if (b >= 0xe0u && b <= 0xefu) return 3;
  if (b >= 0xf0u && b <= 0xf4u) return 4;
  return 0;
}

// Returns the number of bytes consumed at `pos` and fills `sequence` (only
// meaningful when the return value is > 0).  0 means an invalid byte.
inline size_t decodeUtf8(const std::vector<uint8_t>& bytes, size_t pos,
                         size_t* length) {
  const uint8_t b = bytes[pos];
  const uint32_t lead = leadLength(b);
  if (lead == 1) {
    if (b < 0x80u) { *length = 1; return 1; }
    return 0;
  }
  if (lead == 0) return 0;
  if (pos + lead > bytes.size()) return 0;  // truncated at end of input
  // Overlong / surrogate / > U+10FFFF exclusion on the second byte.
  const uint8_t b1 = bytes[pos + 1];
  if (!isContinuation(b1)) return 0;
  if (lead == 2) {
    // C0/C1 are rejected by leadLength; C2-DF + continuation is valid.
    *length = 2;
    return 2;
  }
  if (lead == 3) {
    if (pos + 2 >= bytes.size()) return 0;
    const uint8_t b2 = bytes[pos + 2];
    if (!isContinuation(b2)) return 0;
    if (b == 0xe0u && b1 < 0xa0u) return 0;   // overlong E0 80-9F
    if (b == 0xedu && b1 >= 0xa0u) return 0;  // UTF-16 surrogate half
    *length = 3;
    return 3;
  }
  if (lead == 4) {
    if (pos + 3 >= bytes.size()) return 0;
    const uint8_t b2 = bytes[pos + 2];
    const uint8_t b3 = bytes[pos + 3];
    if (!isContinuation(b2) || !isContinuation(b3)) return 0;
    if (b == 0xf0u && b1 < 0x90u) return 0;   // overlong F0 80-8F
    if (b == 0xf4u && b1 >= 0x90u) return 0;  // > U+10FFFF
    *length = 4;
    return 4;
  }
  return 0;
}

inline void appendHexByte(std::string& out, uint8_t b) {
  static const char kHex[] = "0123456789abcdef";
  out.push_back('\\');
  out.push_back('x');
  out.push_back(kHex[(b >> 4) & 0x0fu]);
  out.push_back(kHex[b & 0x0fu]);
}

}  // namespace detail

inline Utf8Stats utf8StatsOf(const std::vector<uint8_t>& bytes) {
  Utf8Stats stats;
  size_t pos = 0;
  while (pos < bytes.size()) {
    size_t length = 0;
    if (detail::decodeUtf8(bytes, pos, &length) > 0) {
      stats.validBytes += length;
      pos += length;
    } else {
      ++stats.invalidBytes;
      ++stats.escapeSpans;
      pos += 1;
    }
  }
  return stats;
}

inline std::string safeUtf8Display(const std::vector<uint8_t>& bytes,
                                   Utf8Stats* stats) {
  Utf8Stats local;
  std::string out;
  out.reserve(bytes.size());
  size_t pos = 0;
  while (pos < bytes.size()) {
    size_t length = 0;
    if (detail::decodeUtf8(bytes, pos, &length) > 0) {
      out.append(reinterpret_cast<const char*>(bytes.data() + pos), length);
      local.validBytes += length;
      pos += length;
    } else {
      detail::appendHexByte(out, bytes[pos]);
      ++local.invalidBytes;
      ++local.escapeSpans;
      pos += 1;
    }
  }
  if (stats) *stats = local;
  return out;
}

inline std::vector<uint8_t> buildGenerationContext(
    const std::vector<uint8_t>& history, uint32_t tokens,
    uint32_t* padBytes) {
  std::vector<uint8_t> context;
  if (history.size() >= tokens) {
    context.assign(history.end() - tokens, history.end());
    if (padBytes) *padBytes = 0;
  } else {
    const size_t pad = tokens - history.size();
    context.assign(pad, 0x00);
    context.insert(context.end(), history.begin(), history.end());
    if (padBytes) *padBytes = static_cast<uint32_t>(pad);
  }
  return context;
}

inline uint8_t greedyArgmax(const float* logits, uint32_t vocab) {
  uint8_t best = 0;
  if (vocab == 0) return best;
  float bestValue = logits[0];
  for (uint32_t i = 1; i < vocab; ++i) {
    if (logits[i] > bestValue) {
      bestValue = logits[i];
      best = static_cast<uint8_t>(i);
    }
  }
  return best;
}

namespace detail {

// splitmix64 finalizer over a (seed, step) state; deterministic per platform.
inline uint64_t mix64(uint64_t x) {
  x += 0x9E3779B97F4A7C15ull;
  x = (x ^ (x >> 30)) * 0xBF58476D1CE4E5B9ull;
  x = (x ^ (x >> 27)) * 0x94D049BB133111EBull;
  return x ^ (x >> 31);
}

// Top-53-bit uniform sample in [0, 1).
inline double uniform01(uint64_t mixed) {
  return static_cast<double>(mixed >> 11) * 0x1.0p-53;
}

}  // namespace detail

inline uint8_t sampleTopK(const float* logits, uint32_t vocab,
                          float temperature, uint32_t topK, uint64_t seed,
                          uint64_t step) {
  if (vocab == 0) return 0;
  if (!(temperature > 0.0f) || !std::isfinite(temperature))
    return greedyArgmax(logits, vocab);
  const uint32_t k = (topK == 0 || topK >= vocab) ? vocab : topK;
  // Unique total order (logit desc, index asc) makes the top-K selection
  // deterministic across any conforming sort implementation.
  std::vector<uint32_t> indices(vocab);
  for (uint32_t i = 0; i < vocab; ++i) indices[i] = i;
  std::sort(indices.begin(), indices.end(),
            [&](uint32_t a, uint32_t b) {
              const float la = logits[a], lb = logits[b];
              if (la != lb) return la > lb;
              return a < b;
            });
  // Temperature-scaled softmax over the top-K entries in double precision.
  double maxLogit = static_cast<double>(logits[indices[0]]);
  std::vector<double> weights(k);
  double sum = 0.0;
  for (uint32_t i = 0; i < k; ++i) {
    const double w = std::exp((static_cast<double>(logits[indices[i]]) -
                               maxLogit) /
                              static_cast<double>(temperature));
    weights[i] = w;
    sum += w;
  }
  const double u = detail::uniform01(
      detail::mix64(seed + static_cast<uint64_t>(step) * 0x9E3779B97F4A7C15ull));
  double cumulative = 0.0;
  for (uint32_t i = 0; i < k; ++i) {
    cumulative += weights[i] / sum;
    if (u <= cumulative) return static_cast<uint8_t>(indices[i]);
  }
  return static_cast<uint8_t>(indices[k - 1]);
}

inline std::string bytesToHex(const std::vector<uint8_t>& bytes) {
  static const char kHex[] = "0123456789abcdef";
  std::string out;
  out.reserve(bytes.size() * 2);
  for (uint8_t b : bytes) {
    out.push_back(kHex[(b >> 4) & 0x0fu]);
    out.push_back(kHex[b & 0x0fu]);
  }
  return out;
}

inline std::vector<uint8_t> hexToBytes(const std::string& hex) {
  if (hex.size() % 2 != 0)
    throw std::invalid_argument("hex length must be even");
  std::vector<uint8_t> out;
  out.reserve(hex.size() / 2);
  for (size_t i = 0; i < hex.size(); i += 2) {
    auto nibble = [](char c) -> int {
      if (c >= '0' && c <= '9') return c - '0';
      if (c >= 'a' && c <= 'f') return c - 'a' + 10;
      if (c >= 'A' && c <= 'F') return c - 'A' + 10;
      throw std::invalid_argument("invalid hex digit");
    };
    out.push_back(
        static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
  }
  return out;
}

inline const std::vector<ParityPrefix>& parityPrefixes() {
  // Fixed deterministic prefixes (no licensed corpus text).  Prefixes shorter
  // than 32 bytes exercise the NUL-padding branch of the context window.
  static const std::vector<ParityPrefix> kPrefixes = {
      {"japanese_utf8_21",
       {uint8_t(0xE3), uint8_t(0x81), uint8_t(0x93), uint8_t(0xE3),
        uint8_t(0x82), uint8_t(0x93), uint8_t(0xE3), uint8_t(0x81),
        uint8_t(0xAB), uint8_t(0xE3), uint8_t(0x81), uint8_t(0xA1),
        uint8_t(0xE3), uint8_t(0x81), uint8_t(0xAF), uint8_t(0xE3),
        uint8_t(0x80), uint8_t(0x80), uint8_t(0xE4), uint8_t(0xB8),
        uint8_t(0x96)}},  // こんにちは世界
      {"ascii_26",
       {'H', 'e', 'l', 'l', 'o', ',', ' ', 'P', 'h', 'o', 'n', 'e', 'L',
        'M', '!', ' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}},
      {"byte_edges_32",
       {uint8_t(0x00), uint8_t(0x01), uint8_t(0x7f), uint8_t(0x80),
        uint8_t(0xff), uint8_t(0xfe), uint8_t(0x0a), uint8_t(0x09), 'A', 'B',
        'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
        'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X'}},
      {"truncated_utf8_32",
       {uint8_t(0xE6), uint8_t(0x97), uint8_t(0xA5), uint8_t(0xE6),
        uint8_t(0x9C), uint8_t(0xAC), uint8_t(0xE8), uint8_t(0xAA),
        uint8_t(0x9E), uint8_t(0xE3), 'a', 'b', 'c', '1', '2', '3', '4', '5',
        '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8',
        '9'}},
  };
  return kPrefixes;
}

}  // namespace phonelm::nicopedia_gen
