#pragma once

#include "mnn_training_test.h"

#include <atomic>
#include <string>

namespace phonelm {

enum class ExecutionMode : int {
    CPU_REFERENCE = 0,
    MNN_CPU = 1,
    MNN_OPENCL = 2,
    MNN_VULKAN = 3,
    QNN_CPU_FORWARD = 4,
    QNN_HTP_FORWARD = 5,
    QNN_HTP_FORWARD_CPU_BACKWARD = 6,
    QNN_HTP_FORWARD_DW = 7,
    QNN_HTP_FORWARD_DW_DX = 8,
    QNN_HTP_FULL_STEP = 9,
    QNN_HTP_DEVICE_PROBE = 10,
    QNN_CPU_LINEAR_TRAINING = 11,
    QNN_HTP_LINEAR_TRAINING = 12,
    QNN_LINEAR_GRADIENT_CHECK = 13,
    QNN_CPU_MULTIBATCH_TRAINING = 14,
    QNN_HTP_MULTIBATCH_TRAINING = 15,
    QNN_CPU_TRAINING_BENCHMARK = 16,
    QNN_HTP_TRAINING_BENCHMARK = 17,
    QNN_HTP_DW_CHECK = 18,
    QNN_HTP_FORWARD_HTP_DW_TRAINING = 19,
    QNN_HTP_FORWARD_HTP_DW_BENCHMARK = 20,
    QNN_HTP_DX_CHECK = 21,
    QNN_CPU_MLP_TRAINING = 22,
    QNN_HTP_MLP_CPU_BACKWARD = 23,
    QNN_HTP_MLP_HTP_LINEAR_BACKWARD = 24,
    QNN_HTP_MLP_BENCHMARK = 25,
    QNN_MLP_GRADIENT_CHECK = 26,
    QNN_HTP_RELU_BACKWARD_CHECK = 27,
    QNN_HTP_MLP_FUSED_BACKWARD = 28,
    QNN_HTP_MLP_FUSED_BACKWARD_BENCHMARK = 29,
    QNN_HTP_MSE_CHECK = 30,
    QNN_HTP_SGD_CHECK = 31,
    QNN_HTP_MLP_FULL_STEP = 32,
    QNN_HTP_MLP_FULL_STEP_BENCHMARK = 33,
    QNN_HTP_MLP_FULL_STEP_BENCHMARK_CAPTURE = 34,
    QNN_HTP_MLP_FULL_STEP_FAIL_EXECUTE = 35,
    QNN_HTP_MLP_FULL_STEP_FAIL_FINALIZE = 36,
    QNN_HTP_LAYER_NORM_CHECK = 37,
    QNN_HTP_SOFTMAX_CHECK = 38,
    QNN_HTP_ATTENTION_FORWARD_CHECK = 39,
    QNN_HTP_TINY_TRANSFORMER_FORWARD_CHECK = 40,
    QNN_HTP_SOFTMAX_BACKWARD_CHECK = 41,
    QNN_HTP_ATTENTION_BACKWARD_CHECK = 42,
    QNN_HTP_LAYER_NORM_BACKWARD_CHECK = 43,
    QNN_HTP_TINY_TRANSFORMER_TRAINING_STEP = 44,
    QNN_HTP_TINY_TRANSFORMER_TRAINING_MULTI_STEP = 45,
    QNN_HTP_CROSS_ENTROPY_CHECK = 46,
    QNN_HTP_TINY_LANGUAGE_MODEL_STEP = 47,
    QNN_HTP_TINY_LANGUAGE_MODEL_MULTI_STEP = 48,
    QNN_HTP_TINY_LANGUAGE_MODEL_INFERENCE = 49,
    QNN_HTP_TINY_LANGUAGE_MODEL_SGD_CANDIDATE_1 = 50,
    QNN_HTP_TINY_LANGUAGE_MODEL_SGD_CANDIDATE_2 = 51,
    QNN_HTP_TINY_LANGUAGE_MODEL_SGD_CANDIDATE_3 = 52,
    QNN_HTP_TINY_LANGUAGE_MODEL_MOMENTUM_STEP = 53,
    QNN_HTP_TINY_LANGUAGE_MODEL_MOMENTUM_CANDIDATE_1 = 54,
    QNN_HTP_TINY_LANGUAGE_MODEL_MOMENTUM_CANDIDATE_2 = 55,
    QNN_HTP_TINY_LANGUAGE_MODEL_MOMENTUM_INFERENCE = 56,
    QNN_HTP_TINY_LANGUAGE_MODEL_ADAM_STEP = 57,
    QNN_HTP_TINY_LANGUAGE_MODEL_ADAM_CANDIDATE_1 = 58,
    QNN_HTP_TINY_LANGUAGE_MODEL_ADAM_CANDIDATE_2 = 59,
    QNN_HTP_TINY_LANGUAGE_MODEL_ADAM_INFERENCE = 60,
};

const char* executionModeName(ExecutionMode mode);

class TrainingEngine {
public:
    static std::string run(ExecutionMode mode,
                           const TrainingConfig& config,
                           std::atomic_bool& stopRequested,
                           const LogSink& log);
    static std::string capabilityReport();
};

}  // namespace phonelm
